Repository stackrox/acs-fleet-manager, pull requests merged in 2022-10, with the labels that each got.

#461 CI Test Env: Fix timeout issue (hopefully)
  Makefile
Labels: lgtm, approved

#450 Ensure log entries point to relevant code lines
  cmd/fleet-manager/main.go
  fleetshard/pkg/log/log.go
  fleetshard/pkg/runtime/runtime.go
Labels: lgtm, approved

#467 Bump stage fleet shard sync version
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#471 Update fleetshard-sync on prod env
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#414 ROX-12158: Extract authentication mechanics outside of redhatsso/client.go
  .secrets.baseline
  pkg/client/redhatsso/client.go
  pkg/client/redhatsso/client_moq.go
  pkg/client/redhatsso/client_test.go
  pkg/client/redhatsso/integration/client_test.go
  pkg/client/redhatsso/sso_auth_http_client.go
  pkg/services/sso/redhatsso_service.go
  pkg/services/sso/redhatsso_service_test.go
  test/mocks/redhatsso.go
Labels: approved

#407 cleanup TODO(create-ticket) comments
  .golangci.yml
  Makefile
  dp-terraform/add-on/rhacs-terraform/Makefile
  dp-terraform/add-on/rhacs-terraform/config/rbac/role.yaml
  dp-terraform/add-on/rhacs-terraform/pkg/terraform/values/translation/translation.go
  dp-terraform/add-on/rhacs-terraform/pkg/values/translation/values_builder.go
  e2e/e2e_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/converters/resourceutil.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/cluster_placement_strategy.go
  internal/dinosaur/pkg/services/data_plane_cluster.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
  internal/dinosaur/test/integration/require_terms_acceptance_middleware_test.go
Labels: approved

#416 ROX-12157: Implement Create/Delete for dynamic clients in redhatsso client
  .secrets.baseline
  go.mod
  go.sum
  internal/dinosaur/pkg/routes/route_loader.go
  pkg/client/iam/config.go
  pkg/client/redhatsso/client.go
  pkg/client/redhatsso/client_moq.go
  pkg/client/redhatsso/dynamicclients/client.go
  pkg/client/redhatsso/dynamicclients/client_test.go
  pkg/client/redhatsso/integration/client_test.go
  pkg/client/redhatsso/serviceaccounts/client.go
  pkg/client/redhatsso/serviceaccounts/client_test.go
  pkg/client/redhatsso/serviceaccounts/integration/client_test.go
  pkg/services/sso/iam_service.go
  pkg/services/sso/iam_service_moq.go
  pkg/services/sso/redhatsso_service.go
  pkg/services/sso/redhatsso_service_test.go
  test/mocks/redhatsso.go
Labels: approved

#425 ROX-12157: Implement augmentWithDynamicAuthConfig
  .secrets.baseline
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
Labels: lgtm, approved

#468 Minor improvements to terraform script
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#475 Add load test instructions
  e2e/loadtest/README.md
  e2e/loadtest/docker-compose.yml
  e2e/loadtest/locustfile.py
Labels: lgtm, approved

#478 QoL Improvement: Support configurable image refs in Makefile for building and pushing of images
  Makefile
Labels: lgtm, approved

#449 Keep adding groups regardless of failures
  fleetshard/pkg/central/reconciler/init_auth.go
Labels: approved

#480 ROX-12158: fix redhatsso clientId/clientSecret values
  templates/service-template.yml
Labels: lgtm, approved

#481 Simplify deployment setup for infra openshift
  dev/env/defaults/cluster-type-infra-openshift/00-openshift.env
  dev/env/defaults/cluster-type-infra-openshift/env
Labels: lgtm, approved

#456 ROX-12640: Prefer schedule replicas on different nodes
  templates/service-template.yml
Labels: lgtm, approved

#383 Add load testing document link
  docs/architecture/README.md
Labels: approved

#482 Read central-idp-client-secret-file only when static auth is enabled
  internal/dinosaur/pkg/config/central.go
Labels: lgtm, approved

#465 ROX-12650: Update Helm resources in central reconciler
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#486 Fix labelSelector formatting
  templates/service-template.yml
Labels: lgtm, approved

#479 ROX-12946: Remove org_id requirement in Central IdP
  fleetshard/pkg/central/reconciler/init_auth.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  openapi/fleet-manager-private.yaml
Labels: lgtm, approved

#489 Fix label selector
  templates/service-template.yml
Labels: lgtm, approved

#484 Remove update-trigger-like annotations.
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#483 ROX-13017: Deploy a static version of observability resources to prod.
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#490 ROX-10240: Reformat architecture document and add Backup Policy
  docs/architecture/README.md
Labels: approved

#493 bump fleetshard-sync version to fix sso
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#477 ROX-13018: Add an ability to load secrets from Parameter Store for dev / local deployments
  .gitignore
  .openshift-ci/tests/e2e.sh
  dev/env/defaults/00-defaults.env
  dev/env/defaults/cluster-type-openshift-ci/env
  dev/env/manifests/fleet-manager/01-fleet-manager-secrets.yaml
  dev/env/manifests/fleetshard-sync/01-fleetshard-sync-secrets.yaml
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  dev/env/scripts/lib.sh
  docs/development/howto-run-e2e-tests.md
  e2e/README.md
  e2e/e2e_auth_test.go
  e2e/e2e_test.go
  e2e/run_e2e_stage.sh
Labels: lgtm, approved

#372 Use controller-runtime client in `IsRoutesResourceEnabled` function
  e2e/e2e_suite_test.go
  fleetshard/pkg/k8s/client.go
  fleetshard/pkg/k8s/client_test.go
  fleetshard/pkg/runtime/runtime.go
Labels: approved

#495 Add some logs to shed light on AMS failures.
  pkg/client/ocm/client.go
Labels: lgtm

#494 Sync bitwarden cli in terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#491 Use IfNotPresent imagePullPolicy for fleetshard-sync.
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
Labels: approved

#501 ROX-13144: Improve e2e diagnostics and ergonomics
  Makefile
  dev/env/defaults/00-defaults.env
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/down.sh
  dev/env/scripts/lib.sh
  dev/env/scripts/reset
  dev/env/scripts/up.sh
  e2e/e2e_auth_test.go
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
Labels: lgtm, approved

#504 Enable verbose mode for Ginkgo
  .openshift-ci/tests/e2e.sh
Labels: lgtm, approved

#487 Update observability operator to v3.0.16
  dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Labels: lgtm

#508 Remove debug log statement
  pkg/client/ocm/client.go
Labels: lgtm, approved

#512 Test Env: Support static Token
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
Labels: lgtm, approved

#492 ROX-13018: Automate Parameter Store toolset installation
  Makefile
  dev/env/defaults/00-defaults.env
  dev/env/defaults/cluster-type-colima/env
  dev/env/defaults/cluster-type-crc/env
  dev/env/defaults/cluster-type-minikube/env
  dev/env/defaults/cluster-type-rancher-desktop/env
  dev/env/scripts/lib.sh
  dev/env/scripts/up.sh
  docs/development/setup-test-environment.md
  scripts/lib/external_config.sh
  scripts/lib/log.sh
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: approved

#520 Bump fleet shard sync version
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#516 ROX-13274: Scale down scanner default resource requests
  internal/dinosaur/pkg/defaults/default_central_spec.go
  internal/dinosaur/pkg/defaults/default_scanner_spec.go
Labels: approved

#507 ROX-12429 Support debugging deployed Fleet components via VSCode
  .dockerignore
  .gitignore
  .vscode/launch.json
  Dockerfile
  Dockerfile.hybrid
  Makefile
  dev/env/defaults/00-defaults.env
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  dev/env/scripts/lib.sh
  dev/env/scripts/up.sh
Labels: approved

#519 Add Kubernetes Label to Tenant Namespaces
  e2e/e2e_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#511 Support deploying Operator from Quay on remote OpenShift Cluster
  .openshift-ci/tests/e2e.sh
  dev/env/defaults/00-defaults.env
  dev/env/defaults/10-operator-source.env
  dev/env/defaults/cluster-type-openshift/env
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#525 ROX-13290: introduce CHANGELOG.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: lgtm, approved

#472 ROX-12990: Configure default Central resources
  .secrets.baseline
  templates/service-template.yml
Labels: approved

#528 Migrate shared_static_sso -> shared_static_rhsso
  internal/dinosaur/pkg/migrations/202210271100_change_central_client_origin.go
  internal/dinosaur/pkg/migrations/migrations.go
Labels: lgtm, approved

#518 ROX-12076: Probe service for blackbox monitoring [1/3]
  Makefile
  probe/.gitignore
  probe/Dockerfile
  probe/README.md
  probe/cmd/probe/main.go
  probe/config/config.go
  probe/config/config_test.go
  probe/internal/cli/cli.go
  probe/pkg/probe/probe.go
  probe/pkg/runtime/runtime.go
Labels: approved

#517 ROX-12151: cloud accounts endpoint
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/api/public/api_default.go
  internal/dinosaur/pkg/api/public/model_cloud_account.go
  internal/dinosaur/pkg/api/public/model_cloud_accounts_list.go
  internal/dinosaur/pkg/generated/bindata.go
  internal/dinosaur/pkg/handlers/cloud_accounts.go
  internal/dinosaur/pkg/handlers/cloud_accounts_test.go
  internal/dinosaur/pkg/presenters/cloud_accounts.go
  internal/dinosaur/pkg/routes/route_loader.go
  openapi/fleet-manager.yaml
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
Labels: approved

#526 ROX-13098: Load config from Parameter Store for the Dataplane Terraforming
  .shellcheckrc
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved
