Repository stackrox/acs-fleet-manager, pull requests merged in 2022-07, with the labels that each got.

#154 Pass auth config to fleetshard
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/migrations/20220630220500_add_owner_userid_to_centrals.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/manageddinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  pkg/api/manageddinosaurs.manageddinosaur.mas/v1/types.go
  pkg/auth/acs_claims.go
  pkg/auth/context_config.go
Labels: lgtm, approved

#163 Mount stage dataplane configuration file
  templates/service-template.yml
Labels: approved

#167 Add dataplane cluster config configmap
  templates/service-template.yml
Labels: lgtm, approved

#164 ROX-11287: Rename KeycloakService to IAMService.
  internal/dinosaur/pkg/handlers/authentication.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/fleetshard_operator_addon.go
  internal/dinosaur/pkg/workers/dinosaur_mgrs/deleting_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaur_mgrs/ready_dinosaurs_mgr.go
  internal/dinosaur/test/helper.go
  internal/dinosaur/test/integration/admin_dinosaur_test.go
  internal/dinosaur/test/mocks/fleetshardsync/fleetshard-sync.go
  pkg/client/iam/client.go
  pkg/client/iam/client_moq.go
  pkg/client/iam/client_test.go
  pkg/client/iam/config.go
  pkg/client/iam/constants.go
  pkg/client/iam/gocloak_moq.go
  pkg/client/redhatsso/client.go
  pkg/client/redhatsso/client_moq.go
  pkg/client/redhatsso/integration/client_test.go
  pkg/errors/errors.go
  pkg/providers/core.go
  pkg/server/api_server.go
  pkg/services/sso/iam_service.go
  pkg/services/sso/iam_service_moq.go
  pkg/services/sso/keycloak_service_builder.go
  pkg/services/sso/keycloak_service_proxy.go
  pkg/services/sso/redhatsso_service.go
  pkg/services/sso/redhatsso_service_test.go
  test/helper.go
Labels: lgtm, approved

#168 Fix volume indent issue in service template
  templates/service-template.yml
Labels: lgtm, approved

#169 Add dataplane configmap object mapping
  templates/service-template.yml
Labels: lgtm, approved

#151 Add OCM refresh token authentication within fleetshard sync.
  README.md
  config/authentication/jwks-file-static.json
  config/authentication/jwks-file.json
  config/static-token-payload.json
  docs/acs/test-locally-static-token.md
  docs/test-locally-claims.md
  dp-terraform/helm/rhacs-terraform/README.md
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  e2e/e2e_test.go
  fleetshard/README.md
  fleetshard/config/config.go
  fleetshard/config/config_test.go
  fleetshard/main.go
  fleetshard/pkg/fleetmanager/auth.go
  fleetshard/pkg/fleetmanager/auth_ocm.go
  fleetshard/pkg/fleetmanager/auth_rhsso.go
  fleetshard/pkg/fleetmanager/auth_static_token.go
  fleetshard/pkg/fleetmanager/client.go
  fleetshard/pkg/fleetmanager/client_test.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/environments/development.go
  internal/dinosaur/pkg/environments/stage.go
  pkg/server/server_config.go
  templates/service-template.yml
Labels: approved

#170 Use correct file name.
  templates/service-template.yml
Labels: lgtm, approved

#171 Fix identation within the configmap
  templates/service-template.yml
Labels: lgtm, approved

#172 Flatten directory structure for jwks files
  config/jwks-file-static.json
  config/jwks-file.json
  docs/acs/test-locally-static-token.md
  internal/dinosaur/pkg/environments/development.go
  internal/dinosaur/pkg/environments/stage.go
  pkg/server/server_config.go
  templates/service-template.yml
Labels: lgtm

#159 fix central request transition to ready and add e2e for it
  e2e/e2e_test.go
  fleetshard/pkg/centralreconciler/reconciler.go
  fleetshard/pkg/centralreconciler/reconciler_test.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central.go
  internal/dinosaur/pkg/presenters/manageddinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  openapi/fleet-manager-private.yaml
  pkg/api/manageddinosaurs.manageddinosaur.mas/v1/types.go
Labels: approved

#180 Mount kubeconfig from the appSRE vault
  templates/service-template.yml
Labels: lgtm, approved

#176 Move image to values and improve README
  dp-terraform/helm/rhacs-terraform/README.md
  dp-terraform/helm/rhacs-terraform/charts/observability/README.md
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#165 ROX-11287: Remove OSDKeycloakService.
  .github/workflows/ci.yaml
  Makefile
  internal/dinosaur/pkg/environments/development.go
  internal/dinosaur/pkg/environments/integration.go
  internal/dinosaur/pkg/handlers/authentication.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
  internal/dinosaur/test/integration/admin_dinosaur_test.go
  pkg/client/iam/config.go
  pkg/providers/core.go
  pkg/services/sso/iam_service.go
  pkg/services/sso/keycloak_service_builder.go
  pkg/services/sso/keycloak_service_proxy.go
  templates/secrets-template.yml
  templates/service-template.yml
Labels: approved

#184 Fix detect-secrets pre-commit hook.
  .secrets.baseline
  README.md
Labels: lgtm, approved

#183 Drop check for fleetshard-sync rbac existence
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-rbac.yaml
Labels: lgtm, approved

#185 Add golangci-lint pre-commit plugin
  .pre-commit-config.yaml
  README.md
Labels: approved

#186 Add trailing-whitespaces pre-commit plugin
  .github/workflows/openapi_update.yaml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  build_deploy.sh
  config/dataplane-cluster-configuration.yaml
  dev/config/dataplane-cluster-configuration-minikube.yaml
  docs/access-control.md
  docs/acs/test-locally-static-token.md
  docs/adding-a-new-endpoint.md
  docs/adding-new-flags.md
  docs/architecture/quota-service-implementation.md
  docs/automated-testing.md
  docs/complex-string-parsing-and-validation.md
  docs/data-plane-osd-cluster-options.md
  docs/error-handing.md
  docs/feature-flags.md
  docs/getting-credentials-and-accounts.md
  docs/implementation.md
  docs/jwt-claims.md
  docs/observability/README.md
  docs/onboarding-with-service-delivery.md
  docs/populating-configuration.md
  docs/quota-management-list-configuration.md
  docs/running-local-observatorium-token-refresh.md
  docs/slos/README.md
  docs/slos/fleet-manager-api-availability.md
  docs/slos/fleet-manager-api-latency.md
  dp-terraform/helm/rhacs-terraform/README.md
  dp-terraform/helm/rhacs-terraform/charts/observability/README.md
  fleetshard/README.md
  internal/dinosaur/pkg/metrics/component_versions.go
  openapi/fleet-manager-private.yaml
  openapi/fleet-manager.yaml
  pkg/db/README.md
  pr_check_docker.sh
  scripts/cleanup_test_cluster.sh
  templates/route-template.yml
  templates/service-template.yml
Labels: lgtm, approved

#187 Add end-of-file-fixer pre-commit plugin
  .githooks/pre-commit
  .github/workflows/ci.yaml
  .gitleaks.toml
  .pre-commit-config.yaml
  .spectral.yaml
  Makefile
  README.md
  config/deny-list-configuration.yaml
  config/dinosaur-sre-user-list.yaml
  config/provider-configuration.yaml
  config/read-only-user-list.yaml
  dev/config/dataplane-cluster-configuration-dockerdesktop.yaml
  dev/config/dataplane-cluster-configuration-minikube.yaml
  dev/config/provider-configuration-infractl-osd.yaml
  dev/env/central-to-ready/central-request.json
  dev/env/central-to-ready/central-status-update-ready.json
  docs/architecture/data-plane-osd-cluster-dynamic-scaling.md
  docs/observability/README.md
  docs/observability/grafana-dashboard-fleet-manager-metrics.configmap.yaml
  docs/observability/grafana-dashboard-fleet-manager-prod-slos.configmap.yaml
  docs/observability/grafana-dashboard-fleet-manager-stage-slos.configmap.yaml
  docs/slos/fleet-manager-api-availability.md
  docs/slos/fleet-manager-api-latency.md
  internal/dinosaur/pkg/api/admin/private/.travis.yml
  internal/dinosaur/pkg/api/admin/private/git_push.sh
  internal/dinosaur/pkg/api/private/.travis.yml
  internal/dinosaur/pkg/api/private/git_push.sh
  internal/dinosaur/pkg/api/public/.travis.yml
  internal/dinosaur/pkg/api/public/git_push.sh
  openapi/templates/model.mustache
  pr_check_docker.sh
  scripts/extend_staging_osd.sh
  scripts/local_db_teardown.sh
  secrets/db.user
  templates/README.md
  test/support/gitlab-ca.crt
Labels: approved

#188 Add check-json pre-commit plugin
  .pre-commit-config.yaml
  README.md
Labels: approved

#181 Refactor deletion test
  fleetshard/pkg/centralreconciler/reconciler.go
  fleetshard/pkg/centralreconciler/reconciler_test.go
Labels: lgtm, approved

#192 Add code owners
  OWNERS
Labels: lgtm, approved

#191 fix host name generation in fleet-manager
  config/fleetshard-authz-org-ids-development.yaml
  internal/dinosaur/pkg/config/dinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/util.go
  internal/dinosaur/pkg/services/util_test.go
Labels: approved

#193 Run pre-commit hooks in github actions.
  .github/workflows/ci.yaml
  .github/workflows/pre-commit.yaml
  .secrets.baseline
Labels: lgtm, approved

#198 Update .secrets.baseline file.
  .secrets.baseline
Labels: lgtm, approved

#199 Polishing of Test Environment
  .openshift-ci/tests/e2e-test.sh
  .openshift-ci/tests/e2e.sh
  .secrets.baseline
  Makefile
  dev/env/README.md
  dev/env/defaults/00-defaults.env
  dev/env/defaults/01-minikube.env
  dev/env/defaults/10-operator-source.env
  dev/env/defaults/20-imagepullsecrets.env
  dev/env/defaults/cluster-type-infra-openshift/env
  dev/env/defaults/cluster-type-minikube/env
  dev/env/defaults/cluster-type-openshift-ci/00-openshift.env
  dev/env/defaults/cluster-type-openshift-ci/env
  dev/env/defaults/cluster-type-openshift/env
  dev/env/manifests/db/01-db-deployment.yaml
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleetshard-sync/01-fleetshard-sync-deployment.yaml
  dev/env/manifests/shared/01-clusterrole.yaml
  dev/env/manifests/shared/02-clusterrolebinding.yaml
  dev/env/manifests/shared/03-configmap-config.yaml
  dev/env/scripts/apply
  dev/env/scripts/assemble-kubeconfig
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/create-imagepullsecrets
  dev/env/scripts/delete
  dev/env/scripts/down.sh
  dev/env/scripts/lib.sh
  dev/env/scripts/port-forwarding
  dev/env/scripts/retry
  dev/env/scripts/up.sh
Labels: lgtm, approved

#194 Port unit tests and sso-related code changes from KAS-fleet-manager.
  .secrets.baseline
  pkg/client/iam/client.go
  pkg/client/iam/client_moq.go
  pkg/client/redhatsso/client.go
  pkg/client/redhatsso/client_test.go
  pkg/services/sso/iam_service_moq.go
  pkg/services/sso/redhatsso_service.go
  pkg/services/sso/redhatsso_service_test.go
  pkg/shared/http.go
  test/mocks/redhatsso.go
Labels: approved

#178 ROX-11428: Initialise auth provider from fleetshard-sync
  .secrets.baseline
  README.md
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  fleetshard/config/config.go
  fleetshard/pkg/central/client/client.go
  fleetshard/pkg/central/reconciler/init_auth.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/central/reconciler/status.go
  fleetshard/pkg/runtime/runtime.go
  go.mod
  go.sum
Labels: lgtm, approved

#207 ROX-11809: Fix app-interface deployment
  Makefile
  build_deploy.sh
Labels: lgtm, approved

#209 ROX-10835: enable gosec linter, add fixes to suppress warnings
  .golangci.yml
  .secrets.baseline
  internal/dinosaur/pkg/cmd/cloudprovider/providerlist.go
  internal/dinosaur/pkg/cmd/cloudprovider/regionlist.go
  internal/dinosaur/pkg/cmd/errors/list.go
  internal/dinosaur/pkg/converters/cluster.go
  internal/dinosaur/pkg/handlers/cloud_providers.go
  internal/dinosaur/pkg/handlers/data_plane_dinosaur.go
  internal/dinosaur/pkg/presenters/metric.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
  pkg/client/observatorium/api.go
Labels: lgtm, approved

#204 ROX-11802: Support Colima test environment
  Makefile
  dev/env/README.md
  dev/env/defaults/02-infra.env
  dev/env/defaults/03-colima.env
  dev/env/defaults/cluster-type-colima/env
  dev/env/manifests/cluster-type-minikube/06-configmap-config.yaml
  dev/env/scripts/bootstrap.sh
Labels: lgtm, approved

#212 ROX-11469: Add dedicated script for running e2e on stage
  e2e/run_e2e_stage.sh
Labels: lgtm, approved

#214 Don't swallow bootstrapping error logs
  .openshift-ci/tests/e2e-test.sh
  .openshift-ci/tests/e2e.sh
  .secrets.baseline
Labels: lgtm, approved

#210 CI: Use oc instead of kubectl for auto-sensing for infra clusters
  dev/env/defaults/02-infra.env
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#173 Extend build root Dockerfile
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#200 ROX-11716: Initial work on step by step guide to setup OSD cluster
  docs/setup-developer-osd-cluster.md
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#197 ROX-11414: Send routes statuses
  .secrets.baseline
  dev/env/defaults/00-defaults.env
  dev/env/defaults/cluster-type-infra-openshift/env
  dev/env/defaults/cluster-type-openshift/env
  dev/env/manifests/shared/03-configmap-config.yaml
  dev/env/scripts/lib.sh
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/k8s/client.go
  fleetshard/pkg/k8s/constants.go
  fleetshard/pkg/k8s/route.go
  fleetshard/pkg/runtime/runtime.go
  fleetshard/pkg/testutils/k8s.go
  go.mod
  go.sum
  internal/dinosaur/pkg/api/private/model_data_plane_central_status.go
  internal/dinosaur/pkg/presenters/data_plane_dinosaur_status.go
Labels: lgtm, approved

#213 Fix central name collision and improve logs to easier identify central
  fleetshard/pkg/central/client/client.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/runtime/runtime.go
Labels: approved

#208 Docs: Initial docs cleanup
  Makefile
  docs/README.md
  docs/adding-new-flags.md
  docs/architecture/cluster-management-interface-and-implementations.md
  docs/architecture/data-plane-osd-cluster-dynamic-scaling.md
  docs/auth/jwt-claims.md
  docs/automated-testing.md
  docs/deploying-fleet-manager-to-openshift.md
  docs/development/adding-a-new-endpoint.md
  docs/development/customizing-openapi-spec.md
  docs/development/error-handing.md
  docs/development/fleet-manager-component-architecture.png
  docs/development/howto-run-e2e-tests.md
  docs/development/howto-test-fleet-manager.md
  docs/development/implementation.md
  docs/development/populating-configuration.md
  docs/development/test-locally-static-token.md
  docs/development/test-locally-with-fleetshard-sync.md
  docs/getting-credentials-and-accounts.md
  docs/images/cluster-management-abstraction.png
  docs/legacy/access-control.md
  docs/legacy/architecture/quota-service-implementation.md
  docs/legacy/data-plane-osd-cluster-options.md
  docs/legacy/feature-flags.md
  docs/legacy/fleet-shard-pattern.md
  docs/legacy/images/quoata-service.png
  docs/legacy/observability/README.md
  docs/legacy/observability/configuring-metrics-federate-scrape-target.md
  docs/legacy/observability/grafana-dashboard-fleet-manager-metrics.configmap.yaml
  docs/legacy/observability/grafana-dashboard-fleet-manager-prod-slos.configmap.yaml
  docs/legacy/observability/grafana-dashboard-fleet-manager-stage-slos.configmap.yaml
  docs/legacy/observability/running-local-observatorium-token-refresh.md
  docs/legacy/onboarding-with-service-delivery.md
  docs/legacy/quota-management-list-configuration.md
  docs/legacy/slos/README.md
  docs/legacy/slos/fleet-manager-api-availability.md
  docs/legacy/slos/fleet-manager-api-latency.md
  docs/mermaid-diagrams-source/cluster-management-abstraction.mmd
  docs/mermaid-diagrams-source/quoata-service.mmd
  knowledge.md
  pkg/services/queryparser/README.md
  templates/README.md
Labels: approved

#158 ROX-9843: Enable monitoring endpoint for ACS central
  .secrets.baseline
  fleetshard/pkg/central/reconciler/reconciler.go
  go.mod
  go.sum
  internal/dinosaur/pkg/services/clusters_test.go
  internal/dinosaur/pkg/services/quota/quota_management_list_service_test.go
  pkg/workers/leader_election_mgr_test.go
Labels: approved

#211 ROX-11814: Push image to quay
  .openshift-ci/image-push/entrypoint.sh
Labels: lgtm, approved

#220 Increase wait timeout for CI e2e tests
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#225 [CI] Fix container waiting logic
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#231 Use curl --retry when downloading from GitHub during image building
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#228 ROX-11862: Split one host in the private API to frontend and data hosts
  .secrets.baseline
  fleetshard/pkg/central/reconciler/init_auth.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/k8s/route.go
  internal/dinosaur/pkg/api/admin/private/client.go
  internal/dinosaur/pkg/api/admin/private/configuration.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/client.go
  internal/dinosaur/pkg/api/private/configuration.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_data_endpoint.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_ui_endpoint.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_ui_endpoint_tls.go
  internal/dinosaur/pkg/api/public/client.go
  internal/dinosaur/pkg/api/public/configuration.go
  internal/dinosaur/pkg/presenters/manageddinosaur.go
  openapi/fleet-manager-private.yaml
Labels: lgtm, approved

#224 Fix DNS prefix
  internal/dinosaur/constants/cluster.go
Labels: lgtm, approved

#232 Add ocm to Dockerfile.
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#234 Bugfix: Do not return nil in case namespace creation failed
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#236 ROX-11407: Support for Configurable Resource Limits for Central & Scanner
  .secrets.baseline
  dev/env/manifests/shared/03-configmap-config.yaml
  e2e/admin_client_api.go
  e2e/e2e_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_scanner_db.go
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/api/public/model_central_request.go
  internal/dinosaur/pkg/api/public/model_central_request_payload.go
  internal/dinosaur/pkg/api/public/model_central_spec.go
  internal/dinosaur/pkg/api/public/model_resource_list.go
  internal/dinosaur/pkg/api/public/model_resource_requirements.go
  internal/dinosaur/pkg/api/public/model_scanner_spec.go
  internal/dinosaur/pkg/api/public/model_scanner_spec_analyzer.go
  internal/dinosaur/pkg/api/public/model_scanner_spec_analyzer_scaling.go
  internal/dinosaur/pkg/api/public/model_scanner_spec_db.go
  internal/dinosaur/pkg/converters/resourceutil.go
  internal/dinosaur/pkg/generated/bindata.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/migrations/20220728000000_add_resources_to_centrals.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/dinosaur.go
  internal/dinosaur/pkg/presenters/manageddinosaur.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/dinosaur.go
  openapi/fleet-manager-private.yaml
  openapi/fleet-manager.yaml
  pkg/api/manageddinosaurs.manageddinosaur.mas/v1/types.go
Labels: approved

#195 Add E2E test suite for authN/Z.
  .secrets.baseline
  e2e/README.md
  e2e/e2e_auth_test.go
  fleetshard/config/config.go
  fleetshard/config/config_test.go
  fleetshard/main.go
  fleetshard/pkg/fleetmanager/auth_ocm.go
  fleetshard/pkg/fleetmanager/auth_rhsso.go
  fleetshard/pkg/fleetmanager/auth_static_token.go
  pkg/client/redhatsso/client.go
Labels: approved

#222 Add how to run front-end guide
  docs/development/setup-developer-osd-cluster.md
Labels: lgtm, approved

#242 Update OCM version used within CI Dockerfile
  .openshift-ci/build-root/Dockerfile
Labels: approved

#244 fix PodDisruptionBudget maxUnavailable typo
  templates/service-template.yml
Labels: lgtm, approved, needs-ok-to-test

#201 ROX-11441: Run auth E2E tests in pipeline.
  .openshift-ci/tests/e2e.sh
  .secrets.baseline
Labels: approved

#247 ROX-11619: Make issuer configurable
  .secrets.baseline
  fleetshard/pkg/central/reconciler/init_auth.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
  internal/dinosaur/pkg/config/dinosaur.go
  internal/dinosaur/pkg/environments/development.go
  internal/dinosaur/pkg/environments/stage.go
  internal/dinosaur/pkg/presenters/manageddinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  openapi/fleet-manager-private.yaml
  pkg/api/manageddinosaurs.manageddinosaur.mas/v1/types.go
Labels: approved
