Repository stackrox/acs-fleet-manager, pull requests merged in 2022-11, with the labels that each got.

#538 Build for machine architecture instead of amd64
  Makefile
Labels: lgtm, approved

#537 ROX-13220: Test Github OIDC provider on AWS
  .github/workflows/deploy-qa.yaml
Labels: lgtm, approved

#523 Integrate EditorConfig
  .editorconfig
  README.md
Labels: lgtm, approved

#531 ROX-13098: Load secrets in IDP cluster creation script to Parameter Store
  CHANGELOG.md
  docs/development/secret-management.md
  docs/development/setup-osd-cluster-idp.md
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/osd-cluster-idp-setup.sh
  scripts/lib/external_config.sh
Labels: approved

#540 Rename QA environment to stage
  .github/workflows/deploy-stage.yaml
Labels: lgtm, approved

#527 ROX-13004: Sync CRDs with the stackrox repo
  dev/env/manifests/crds/01-platform.stackrox.io_centrals.yaml
  dev/env/manifests/crds/02-platform.stackrox.io_securedclusters.yaml
Labels: approved

#505 ROX-12689: oc login automatically, drop need for ocm login
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/osd-cluster-idp-setup.sh
Labels: lgtm, approved

#548 ROX-12689: Trim whitespace around URL
  dp-terraform/osd-cluster-idp-setup.sh
Labels: lgtm, approved

#550 ROX-13436: remove --debug to stop echoing secrets
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#541 ROX-12480: run terraform script from a github action
  .github/workflows/deploy-stage.yaml
Labels: lgtm, approved

#549 Upgrade go version to 1.18 for app-interface CI
  Makefile
  build_deploy.sh
Labels: lgtm, approved

#532 ROX-12076: Probe service - add clients [2]
  pkg/client/fleetmanager/client.go
  pkg/client/fleetmanager/client_moq.go
  probe/config/config.go
  probe/pkg/fleetmanager/client.go
Labels: approved

#533 ROX-12076: Probe service - probe requests [3]
  probe/config/config.go
  probe/config/config_test.go
  probe/internal/cli/cli.go
  probe/internal/cli/cli_test.go
  probe/pkg/probe/probe.go
  probe/pkg/probe/probe_moq.go
  probe/pkg/probe/probe_test.go
  probe/pkg/runtime/runtime.go
  probe/pkg/runtime/runtime_test.go
Labels: approved

#559 Fix app-interface docker build
  Dockerfile
Labels: lgtm, approved

#561 Move cluster params to the Parameter Store
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#564 Bump fleet-manager image version for the DP terraforming
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#563 probe service: use correct context when invoking the cleanup
  probe/pkg/runtime/runtime.go
  probe/pkg/runtime/runtime_test.go
Labels: approved

#555 ROX-13004: Update Stackrox reference in go.mod
  fleetshard/pkg/central/reconciler/proxy_test.go
  go.mod
  go.sum
  internal/dinosaur/pkg/services/clusters_test.go
Labels: lgtm, approved

#575 Fix stern dependency in the build image
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#576 Add probe directory to depenabot config
  .github/dependabot.yaml
Labels: lgtm

#579 ROX-13408: Remove api.iam.acs scope in token request
  openapi/rh-sso-dynamic-client.yaml
  pkg/client/redhatsso/api/api/openapi.yaml
  pkg/client/redhatsso/api/api_acs_tenants.go
  pkg/client/redhatsso/api/model_acs_client_response_data.go
  pkg/client/redhatsso/dynamicclients/client.go
Labels: approved

#580 Fix removal of centrals that did not get assigned a client origin
  internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go
Labels: lgtm, approved

#566 ROX-12076: docker image for probe service [5]
  .github/workflows/ci.yaml
  Makefile
  build_deploy.sh
  probe/Dockerfile
Labels: lgtm, approved

#583 fix quay user typo in ci action
  .github/workflows/ci.yaml
  build_deploy.sh
Labels: lgtm

#568 ROX-12076: Remove probe name prefix [6]
  probe/config/config.go
  probe/internal/cli/cli_test.go
  probe/pkg/probe/probe.go
  probe/pkg/probe/probe_test.go
  probe/pkg/runtime/runtime_test.go
Labels: approved

#582 ROX-12076: OCM auth [8]
  deploy/helm/probe/templates/01-operator-02-secret-ocm-token.yaml
  deploy/helm/probe/templates/01-operator-02-secret-rhsso-client-secret.yaml
  deploy/helm/probe/templates/01-operator-03-deployment.yaml
  deploy/helm/probe/values.yaml
  probe/config/config.go
  probe/config/config_test.go
  probe/internal/cli/cli.go
  probe/pkg/fleetmanager/client.go
  probe/pkg/probe/probe.go
  probe/pkg/probe/probe_test.go
Labels: approved

#535 ROX-12153: Add cloud account id to API, database and AMS call
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/model_central_request.go
  internal/dinosaur/pkg/api/admin/private/model_central_request_payload.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/api/public/model_central_request.go
  internal/dinosaur/pkg/api/public/model_central_request_payload.go
  internal/dinosaur/pkg/generated/bindata.go
  internal/dinosaur/pkg/handlers/cloud_accounts.go
  internal/dinosaur/pkg/handlers/cloud_accounts_test.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/migrations/202010311200_add_cloud_account_to_central_request.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/dinosaur.go
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
  openapi/fleet-manager.yaml
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
  pkg/errors/errors.go
Labels: lgtm, approved

#584 Simplify the script a little.
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#585 ROX-12076: Add continuous deployment for probe [9]
  .github/workflows/deploy-stage.yaml
  deploy/helm/probe/deploy.sh
  deploy/helm/probe/templates/01-operator-04-deployment.yaml
Labels: lgtm, approved

#593 Remove dinosaur references in data_plane_dinosaur.go
  internal/dinosaur/pkg/handlers/data_plane_dinosaur.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/data_plane_dinosaur.go
  internal/dinosaur/providers.go
Labels: lgtm, approved

#595 Split building image scripts
  .github/workflows/ci.yaml
  build_push_fleet_manager.sh
  build_push_probe.sh
Labels: lgtm, approved

#592 update observability resources to b864d5f
  dp-terraform/helm/rhacs-terraform/charts/observability/README.md
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm

#598 ROX-13607: Temporary transitional script.
  build_deploy.sh
Labels: lgtm, approved

#565 ROX-12871: add release-version to Makefile
  CHANGELOG.md
  Makefile
Labels: lgtm, approved

#599 Drop temporary build and deploy script
  build_deploy.sh
Labels: lgtm, approved

#596 bump fleetshard-sync image for stage environment
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#600 Remove dinosaur references in accepted_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_dinosaurs_mgr.go
  internal/dinosaur/providers.go
Labels: lgtm, approved

#544 ROX-13396: Add SAML authentication method for AWS
  .github/workflows/deploy-stage.yaml
  Makefile
  dev/env/defaults/00-defaults.env
  dev/env/defaults/cluster-type-colima/env
  dev/env/defaults/cluster-type-crc/env
  dev/env/defaults/cluster-type-minikube/env
  dev/env/defaults/cluster-type-rancher-desktop/env
  dev/env/scripts/lib.sh
  dev/env/scripts/up.sh
  docs/development/secret-management.md
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/osd-cluster-idp-setup.sh
  scripts/lib/external_config.sh
  tools/requirements.txt
Labels: approved

#601 Fix `release-version` makefile target
  Makefile
Labels: lgtm, approved

#608 Another test
  .github/workflows/deploy-stage.yaml
  Makefile
  dev/env/defaults/00-defaults.env
  dev/env/defaults/cluster-type-colima/env
  dev/env/defaults/cluster-type-crc/env
  dev/env/defaults/cluster-type-minikube/env
  dev/env/defaults/cluster-type-rancher-desktop/env
  dev/env/scripts/lib.sh
  dev/env/scripts/up.sh
  docs/development/secret-management.md
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/osd-cluster-idp-setup.sh
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_dinosaurs_mgr.go
  internal/dinosaur/providers.go
  probe/Dockerfile
  scripts/lib/external_config.sh
  tools/requirements.txt
Labels: lgtm, approved

#604 ROX-13396: Add a warning message when there are no parameters for a service
  scripts/lib/external_config.sh
Labels: approved

#603 ROX-13621 Write cluster params to Parameter Store on cluster IDP setup
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/osd-cluster-idp-setup.sh
Labels: lgtm, approved

#605 ROX-12411: Make staging e2e use probe service
  Makefile
  e2e/run_e2e_stage.sh
Labels: lgtm, approved

#610 Fix drop tty requirement from e2e staging run
  Makefile
Labels: lgtm, approved

#609 Switch auth type to RHSSO by default for fleetshard-sync
  dev/env/defaults/00-defaults.env
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  dev/env/scripts/lib.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
  fleetshard/README.md
  fleetshard/config/config.go
  fleetshard/config/config_test.go
  fleetshard/main.go
Labels: lgtm, approved

#586 Make image for E2E tests instead of Base build image
  .dockerignore
  .openshift-ci/e2e-runtime/Dockerfile
  .openshift-ci/e2e-runtime/docker_run_e2e.sh
  .openshift-ci/e2e-runtime/e2e_dockerized.sh
  Dockerfile
  Makefile
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/docker.sh
  dev/env/scripts/lib.sh
  dev/env/scripts/up.sh
  docs/development/setup-test-environment.md
Labels: lgtm, approved

#611 ROX-13450: Wait for docker image to appear before terraforming.
  dp-terraform/helm/rhacs-terraform/check_image_exists.sh
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#619 Allow retrieval of ID tokens within fleetmanager auth
  pkg/client/fleetmanager/auth.go
  pkg/client/fleetmanager/auth_ocm.go
  pkg/client/fleetmanager/auth_rhsso.go
  pkg/client/fleetmanager/auth_static_token.go
Labels: approved

#624 Fix probe deployment
  deploy/helm/probe/deploy.sh
Labels: lgtm, approved

#625 Fix up.sh script
  .openshift-ci/e2e-runtime/e2e_dockerized.sh
  dev/env/scripts/docker.sh
Labels: lgtm, approved
