Repository stackrox/acs-fleet-manager, pull requests merged in 2022-08, with the labels that each got.

#196 added cluster config for local CRC
  dev/config/dataplane-cluster-configuration-crc.yaml
Labels: lgtm, approved

#229 Fix colima test environment and review leftovers
  dev/env/defaults/cluster-type-colima/env
  dev/env/defaults/cluster-type-infra-openshift/env
  dev/env/defaults/cluster-type-openshift/env
Labels: lgtm, approved

#246 ROX-12012: Additional config for auth provider
  .secrets.baseline
  fleetshard/pkg/central/reconciler/init_auth.go
Labels: approved

#218 Allow for disabling leader election for test environments
  .openshift-ci/tests/e2e-test.sh
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  pkg/server/server_config.go
  pkg/workers/leader_election_mgr.go
Labels: lgtm, approved

#245 Use STATIC_OCM_TOKEN instead of regular one in e2e staging tests
  e2e/run_e2e_stage.sh
Labels: lgtm, approved

#248 Embed centos repo configuration in Dockerfile
  .openshift-ci/build-root/Dockerfile
  .openshift-ci/build-root/centos.repo
Labels: lgtm, approved

#237 ROX-11862: Remove redundant conversion layer (ManagedCentralCR)
  .secrets.baseline
  internal/dinosaur/pkg/handlers/data_plane_dinosaur.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/dinosaurservice_moq.go
  internal/dinosaur/providers.go
  pkg/api/manageddinosaurs.manageddinosaur.mas/v1/types.go
Labels: approved

#249 Remove heredoc from Dockerfile
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#250 Install git in custom root image
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#251 Add AppStream repo to CentOS root image
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#255 Centos image: Install jq
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#256 CentOS root image: Install gcc
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#230 Use gotestsum in CI
  Makefile
  dev/env/defaults/cluster-type-openshift-ci/env
Labels: lgtm, approved

#238 ROX-11862: Match DNS name to the ADR
  .secrets.baseline
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/k8s/route.go
  fleetshard/pkg/testutils/k8s.go
  internal/dinosaur/constants/cluster.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/dbapi/data_plane_central_status.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_data_plane_central_status_routes.go
  internal/dinosaur/pkg/presenters/data_plane_dinosaur_status.go
  internal/dinosaur/pkg/presenters/dinosaur.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/data_plane_dinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/util.go
  openapi/fleet-manager-private.yaml
Labels: approved

#239 ROX-11917: Create passthrough route from the fleetshard sync
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/k8s/route.go
Labels: approved

#257 CI E2E Tests: Make sure that RUN_AUTH_E2E variable is initialized
  .openshift-ci/tests/e2e.sh
  .secrets.baseline
Labels: lgtm, approved

#258 Test Env: Add additional wait during setting up of the operator
  dev/env/scripts/bootstrap.sh
Labels: lgtm, approved

#260 Add ticket numbers
  e2e/e2e_test.go
Labels: lgtm, approved

#261 Add Vlad to OWNERS file
  OWNERS
Labels: lgtm, approved

#263 do not skip all tests if RUN_AUTH_E2E not set
  e2e/e2e_auth_test.go
Labels: lgtm, approved

#241 added DNS e2e tests
  dev/env/defaults/00-defaults.env
  dev/env/defaults/04-crc.env
  dev/env/defaults/cluster-type-crc/00-openshift.env
  dev/env/defaults/cluster-type-crc/env
  dev/env/defaults/cluster-type-openshift-ci/env
  dev/env/defaults/cluster-type-openshift/env
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/scripts/lib.sh
  dev/env/scripts/up.sh
  docs/development/howto-run-e2e-tests.md
  docs/how-to-get-certificates.md
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
Labels: lgtm, approved

#266 Add debug env print
  e2e/run_e2e_stage.sh
Labels: lgtm, approved

#269 Test Env: Support Rancher Desktop
  dev/env/defaults/04-rancher-desktop.env
  dev/env/defaults/cluster-type-rancher-desktop/env
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#272 Fix typo in test env for rancher desktop
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#264 ROX-12009: Remove update central call from public API
  .secrets.baseline
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/api/public/api_default.go
  internal/dinosaur/pkg/api/public/model_central_update_request.go
  internal/dinosaur/pkg/generated/bindata.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/routes/route_loader.go
  openapi/fleet-manager.yaml
Labels: lgtm, approved

#226 Small fixes for setup dev OSD cluster guide
  docs/development/setup-developer-osd-cluster.md
Labels: lgtm, approved

#254 ROX-12052: Routes on vanilla k8s
  Makefile
  README.md
  dev/env/manifests/ingress-router/dummy.crd.yaml
  docs/development/test-locally-route-hosts.md
  scripts/ingress-router.sh
Labels: lgtm, approved

#262 ROX-11987: Migrate admin API middleware to internal SSO
  .secrets.baseline
  config/admin-authz-roles-dev.yaml
  config/admin-authz-roles-prod.yaml
  dev/env/manifests/shared/03-configmap-config.yaml
  internal/dinosaur/pkg/environments/development.go
  internal/dinosaur/pkg/environments/stage.go
  internal/dinosaur/pkg/handlers/authentication.go
  internal/dinosaur/pkg/routes/route_loader.go
  pkg/auth/roles_authz.go
  pkg/auth/roles_authz_middleware.go
  pkg/auth/roles_authz_middleware_test.go
  pkg/client/iam/config.go
  pkg/providers/core.go
  templates/service-template.yml
Labels: approved

#278 Fix identation in config map
  templates/service-template.yml
Labels: lgtm, approved

#273 Add re-terraform steps to README
  dp-terraform/helm/rhacs-terraform/README.md
Labels: lgtm, approved

#227 ROX-11934: Fix DB status for Central stays on deprovision
  .secrets.baseline
  internal/dinosaur/pkg/services/dinosaur.go
Labels: approved

#243 ROX-11407: Support for Configurable Resource Limits for Central & Scanner
  .openshift-ci/tests/e2e.sh
  .secrets.baseline
  dev/env/manifests/shared/03-configmap-config.yaml
  e2e/admin_client_api.go
  e2e/e2e_test.go
  e2e/envtokenauth/auth_env_token.go
  fleetshard/pkg/central/reconciler/reconciler.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/dbapi/central_spec.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_scanner_db.go
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/api/public/model_central_request.go
  internal/dinosaur/pkg/api/public/model_central_request_payload.go
  internal/dinosaur/pkg/api/public/model_central_spec.go
  internal/dinosaur/pkg/api/public/model_resource_list.go
  internal/dinosaur/pkg/api/public/model_resource_requirements.go
  internal/dinosaur/pkg/api/public/model_scanner_spec.go
  internal/dinosaur/pkg/api/public/model_scanner_spec_analyzer.go
  internal/dinosaur/pkg/api/public/model_scanner_spec_analyzer_scaling.go
  internal/dinosaur/pkg/api/public/model_scanner_spec_db.go
  internal/dinosaur/pkg/config/dataplane_cluster_config.go
  internal/dinosaur/pkg/converters/resourceutil.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/migrations/20220728000000_add_resources_to_centrals.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/dinosaur.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/routes/route_loader.go
  openapi/fleet-manager-private.yaml
  openapi/fleet-manager.yaml
  pkg/auth/roles_authz.go
Labels: lgtm, approved

#150 ROX-11552 - Skeleton of add-on operator for terraforming
  dp-terraform/add-on/rhacs-terraform/.dockerignore
  dp-terraform/add-on/rhacs-terraform/.gitignore
  dp-terraform/add-on/rhacs-terraform/Dockerfile
  dp-terraform/add-on/rhacs-terraform/Makefile
  dp-terraform/add-on/rhacs-terraform/PROJECT
  dp-terraform/add-on/rhacs-terraform/README.md
  dp-terraform/add-on/rhacs-terraform/api/v1alpha1/terraform_types.go
  dp-terraform/add-on/rhacs-terraform/config/crd/bases/dataplane.acs.rhcloud.com_terraforms.yaml
  dp-terraform/add-on/rhacs-terraform/config/crd/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/default/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/default/manager_auth_proxy_patch.yaml
  dp-terraform/add-on/rhacs-terraform/config/default/manager_config_patch.yaml
  dp-terraform/add-on/rhacs-terraform/config/manager/controller_manager_config.yaml
  dp-terraform/add-on/rhacs-terraform/config/manager/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/manager/manager.yaml
  dp-terraform/add-on/rhacs-terraform/config/manifests/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/prometheus/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/prometheus/monitor.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/auth_proxy_client_clusterrole.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/auth_proxy_role.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/auth_proxy_role_binding.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/auth_proxy_service.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/leader_election_role.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/leader_election_role_binding.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/role.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/role_binding.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/service_account.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/terraform_editor_role.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/terraform_viewer_role.yaml
  dp-terraform/add-on/rhacs-terraform/config/samples/dataplane_v1alpha1_terraform.yaml
  dp-terraform/add-on/rhacs-terraform/config/samples/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/scorecard/bases/config.yaml
  dp-terraform/add-on/rhacs-terraform/config/scorecard/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/scorecard/patches/basic.config.yaml
  dp-terraform/add-on/rhacs-terraform/config/scorecard/patches/olm.config.yaml
  dp-terraform/add-on/rhacs-terraform/go.mod
  dp-terraform/add-on/rhacs-terraform/go.sum
  dp-terraform/add-on/rhacs-terraform/hack/boilerplate.go.txt
  dp-terraform/add-on/rhacs-terraform/main.go
  dp-terraform/add-on/rhacs-terraform/pkg/terraform/values/translation/translation.go
  dp-terraform/add-on/rhacs-terraform/pkg/values/translation/utils.go
  dp-terraform/add-on/rhacs-terraform/pkg/values/translation/values_builder.go
  dp-terraform/add-on/rhacs-terraform/watches.yaml
Labels: lgtm, approved

#280 [CI Test Env] Prevent access to uninitialized variable and simplify propagation of static token
  .openshift-ci/tests/e2e.sh
Labels: approved

#279 Include pre-commit hook for verifying that generated files are up-to-date
  .github/workflows/pre-commit.yaml
  .pre-commit-config.yaml
  scripts/generated-files-uptodate.sh
Labels: lgtm, approved

#283 Add dinosaur counter badge to README.md
  README.md
Labels: approved

#276 ROX-12104: Comment false positive secrets in code
  .secrets.baseline
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleetshard-sync/01-fleetshard-sync-deployment.yaml
  dev/env/scripts/bootstrap.sh
  e2e/e2e_auth_test.go
  fleetshard/pkg/central/reconciler/init_auth.go
  fleetshard/pkg/k8s/route.go
  fleetshard/pkg/testutils/k8s.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/clusters/ocm_provider_test.go
  internal/dinosaur/pkg/clusters/standalone_provider.go
  internal/dinosaur/pkg/clusters/standalone_provider_test.go
  internal/dinosaur/pkg/config/aws.go
  internal/dinosaur/pkg/services/clusters_test.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/fleetshard_operator_addon.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
  openapi/fleet-manager-private.yaml
  openapi/fleet-manager.yaml
  pkg/auth/helper.go
  pkg/client/iam/config.go
  pkg/client/iam/constants.go
  pkg/client/observatorium/observability_config.go
  pkg/client/ocm/config.go
  pkg/client/redhatsso/client_test.go
  pkg/db/config.go
  pkg/server/logging/writer.go
  pkg/services/sso/redhatsso_service_test.go
  templates/service-template.yml
  test/helper.go
  test/mocks/redhatsso.go
Labels: lgtm, approved

#275 ROX-12104: Cleanup secrets in ci.yaml
  .github/workflows/ci.yaml
  .secrets.baseline
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleetshard-sync/01-fleetshard-sync-deployment.yaml
  dev/env/scripts/bootstrap.sh
  docker/Dockerfile_template
  docker/Dockerfile_template_mocked
  e2e/e2e_auth_test.go
  fleetshard/pkg/central/reconciler/init_auth.go
  fleetshard/pkg/k8s/route.go
  fleetshard/pkg/testutils/k8s.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/clusters/ocm_provider_test.go
  internal/dinosaur/pkg/clusters/standalone_provider.go
  internal/dinosaur/pkg/clusters/standalone_provider_test.go
  internal/dinosaur/pkg/config/aws.go
  internal/dinosaur/pkg/services/clusters_test.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/fleetshard_operator_addon.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
  openapi/fleet-manager-private.yaml
  openapi/fleet-manager.yaml
  pkg/auth/helper.go
  pkg/client/iam/config.go
  pkg/client/iam/constants.go
  pkg/client/observatorium/observability_config.go
  pkg/client/ocm/config.go
  pkg/client/redhatsso/client_test.go
  pkg/db/config.go
  pkg/server/logging/writer.go
  pkg/services/sso/redhatsso_service_test.go
  pr_check_docker.sh
  templates/service-template.yml
  test/helper.go
  test/mocks/redhatsso.go
Labels: approved

#285 Update containerd dependency [dependabot]
  dp-terraform/add-on/rhacs-terraform/go.mod
  dp-terraform/add-on/rhacs-terraform/go.sum
Labels: lgtm, approved

#288 Add missing openapi endpoint & prevent formatting of generated files
  .pre-commit-config.yaml
  dp-terraform/add-on/rhacs-terraform/Makefile
  dp-terraform/add-on/rhacs-terraform/README.md
  dp-terraform/add-on/rhacs-terraform/config/crd/bases/dataplane.acs.rhcloud.com_terraforms.yaml
  dp-terraform/add-on/rhacs-terraform/config/manager/controller_manager_config.yaml
  dp-terraform/add-on/rhacs-terraform/config/samples/dataplane_v1alpha1_terraform.yaml
  dp-terraform/add-on/rhacs-terraform/hack/boilerplate.go.txt
  dp-terraform/add-on/rhacs-terraform/pkg/terraform/values/translation/translation.go
  internal/dinosaur/pkg/api/admin/private/.travis.yml
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/api_default.go
  internal/dinosaur/pkg/api/admin/private/git_push.sh
  internal/dinosaur/pkg/api/admin/private/model_central_request.go
  internal/dinosaur/pkg/api/admin/private/model_central_request_payload.go
  internal/dinosaur/pkg/api/admin/private/model_central_spec.go
  internal/dinosaur/pkg/api/admin/private/model_resource_list.go
  internal/dinosaur/pkg/api/admin/private/model_resource_requirements.go
  internal/dinosaur/pkg/api/admin/private/model_scanner_spec.go
  internal/dinosaur/pkg/api/admin/private/model_scanner_spec_analyzer.go
  internal/dinosaur/pkg/api/admin/private/model_scanner_spec_analyzer_scaling.go
  internal/dinosaur/pkg/api/admin/private/model_scanner_spec_db.go
  internal/dinosaur/pkg/api/private/.travis.yml
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/git_push.sh
  internal/dinosaur/pkg/api/public/.travis.yml
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/api/public/git_push.sh
  internal/dinosaur/pkg/generated/bindata.go
  openapi/fleet-manager-private-admin.yaml
  openapi/fleet-manager-private.yaml
  openapi/fleet-manager.yaml
Labels: lgtm, approved

#292 Configure AMS quota backend
  docs/development/populating-configuration.md
  docs/legacy/quota-management-list-configuration.md
  docs/quota/quota-flow.png
  docs/quota/quota.md
  e2e/e2e_test.go
  internal/dinosaur/pkg/environments/production.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
  pkg/client/ocm/types.go
Labels: lgtm, approved

#294 TEMPORARY Add rollback command to drop stage RDS
  templates/service-template.yml
Labels: lgtm, approved

#297 ROX-12215 - ACS operator use manual install approval plan
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Labels: lgtm, approved

#284 Add security checklist item to pull request template
  .github/pull_request_template.md
Labels: approved

#301 ROX-11614: Add PagerDuty secret to the observability helm chart
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-pagerduty.yaml
  dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm

#291 ROX-12074: Implement endpoint for updating central resource settings
  docs/development/howto-run-e2e-tests.md
  e2e/admin_client_api.go
  e2e/e2e_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/model_dinosaur_update_request.go
  internal/dinosaur/pkg/api/admin/private/model_resource_list.go
  internal/dinosaur/pkg/api/admin/private/model_resource_requirements.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/dbapi/central_spec.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_resource_list.go
  internal/dinosaur/pkg/api/private/model_resource_requirements.go
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/api/public/model_resource_list.go
  internal/dinosaur/pkg/api/public/model_resource_requirements.go
  internal/dinosaur/pkg/converters/resourceutil.go
  internal/dinosaur/pkg/converters/resourceutil_test.go
  internal/dinosaur/pkg/defaults/default_central_spec.go
  internal/dinosaur/pkg/defaults/default_scanner_spec.go
  internal/dinosaur/pkg/generated/bindata.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/presenters/dinosaur.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/dinosaur.go
  openapi/fleet-manager-private-admin.yaml
  openapi/fleet-manager-private.yaml
  openapi/fleet-manager.yaml
Labels: lgtm, approved

#300 Improve error output in bootstrap script in case K8s cannot be reached
  dev/env/scripts/bootstrap.sh
Labels: lgtm, approved

#303 Don't forget to capture output of kubectl sanity check
  dev/env/scripts/bootstrap.sh
Labels: lgtm, approved

#296 Update observability operator to v3.0.14
  dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Labels: lgtm, approved

#265 Disable admin password once sso.redhat.com auth provider is initialised
  .secrets.baseline
  fleetshard/pkg/central/client/client.go
  fleetshard/pkg/central/reconciler/init_auth.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  go.mod
  go.sum
Labels: approved

#308 Revert "TEMPORARY Add rollback command to drop stage RDS"
  templates/service-template.yml
Labels: lgtm, approved

#313 Use vault secret for dataplane certificate
  templates/service-template.yml
Labels: lgtm, approved

#305 Make e2e test output more verbose
  dev/env/defaults/cluster-type-openshift-ci/env
Labels: lgtm, approved

#317 Reconcile ClusterDNS
  internal/dinosaur/pkg/config/dataplane_cluster_config.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
Labels: lgtm, approved

#307 ROX-12284: Return proper admin dinosaur object when updating dinosaur via admin API
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/model_central_request.go
  internal/dinosaur/pkg/api/admin/private/model_dinosaur.go
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/api/public/model_central_request.go
  internal/dinosaur/pkg/converters/resourceutil.go
  internal/dinosaur/pkg/generated/bindata.go
  internal/dinosaur/pkg/presenters/admin_dinosaur.go
  internal/dinosaur/pkg/presenters/dinosaur.go
  openapi/fleet-manager-private-admin.yaml
  openapi/fleet-manager.yaml
Labels: lgtm, approved

#306 Read data plane cluster id for staging e2e from env
  e2e/run_e2e_stage.sh
Labels: lgtm, approved

#322 Allow updating manual cluster configuration in fleet-manager's DB
  internal/dinosaur/pkg/workers/clusters_mgr.go
Labels: lgtm, approved

#298 Update README with installation one-liner for helm diff
  dp-terraform/helm/rhacs-terraform/README.md
Labels: lgtm, approved

#320 enable external dns and tls for appinterface template
  templates/service-template.yml
Labels: lgtm, approved

#325 CI build root image: Change dnf update command
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#326 fix secret reference for aws stage
  templates/service-template.yml
Labels: lgtm, approved

#286 ROX-12052: Add script commands for quickly adding/removing hostnames locally
  docs/development/test-locally-route-hosts.md
  scripts/ingress-router.sh
Labels: lgtm, approved

#293 Fix reconcile cache
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#289 ROX-11729: Add unit tests to ensure that routes are sent at once
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/testutils/k8s.go
Labels: lgtm, approved

#324 Use ginkgo instead of gotestsum for e2e test suite
  .openshift-ci/tests/e2e.sh
  Makefile
  go.mod
  go.sum
Labels: lgtm, approved

#328 Get rid of vendor directory
  Makefile
  pkg/client/iam/client.go
  pkg/client/iam/gocloak_moq.go
Labels: lgtm, approved

#329 ROX-11939: Enable Scanner monitoring exposure
  fleetshard/pkg/central/reconciler/reconciler.go
  go.mod
  go.sum
  pkg/client/observatorium/api_mock.go
Labels: lgtm, approved

#221 Update README
  Makefile
  README.md
  docs/development/git-hooks.md
  docs/development/running-fleet-manager.md
Labels: lgtm, approved

#330 Bump github.com/prometheus/client_golang from 1.12.2 to 1.13.0
  go.mod
  go.sum
  pkg/client/observatorium/api_mock.go
  pkg/client/observatorium/api_moq.go
Labels: lgtm, approved

#267 ROX-12072: Route update optimizations
  fleetshard/pkg/central/reconciler/errors.go
  fleetshard/pkg/central/reconciler/init_auth.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/k8s/route.go
  fleetshard/pkg/runtime/runtime.go
Labels: lgtm, approved

#335 Bump github.com/redhat-developer/app-services-sdk-go/serviceaccounts from 0.4.0 to 0.5.0
  go.mod
  go.sum
  pkg/client/redhatsso/client.go
  test/mocks/redhatsso.go
Labels: lgtm, approved

#340 Delete leftover namespaces in down script
  dev/env/scripts/down.sh
Labels: approved

#350 ROX-12143: Install OpenShift Router on Vanilla K8s
  Makefile
  README.md
  dev/env/defaults/00-defaults.env
  dev/env/defaults/cluster-type-openshift/env
  dev/env/manifests/openshift-router/00-apps-openshift-dummy.crd.yaml
  dev/env/manifests/openshift-router/01-router_rbac.yaml
  dev/env/manifests/openshift-router/02-route.crd.yaml
  dev/env/manifests/openshift-router/03-router.yaml
  dev/env/manifests/openshift-router/README.md
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/lib.sh
  docs/development/test-locally-route-hosts.md
  scripts/openshift-router.sh
Labels: lgtm, approved

#348 Work around docker.io outages
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/lib.sh
  dev/env/scripts/up.sh
Labels: approved

#304 Add script to pull secrets and terraform data plane clusters
  dp-terraform/helm/rhacs-terraform/README.md
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved
