Repository stackrox/acs-fleet-manager, pull requests merged in 2022-12, with the labels that each got.

#612 ROX-13648: Compute - rather than hardcode - the image tag.
  CHANGELOG.md
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#620 ROX-13408: Comment to clarify usage of api.iam.acs/api.iam.clients scope
  pkg/client/redhatsso/dynamicclients/client.go
Labels: approved

#542 ROX-13004: Provision RDS instances and clusters
  dev/env/manifests/fleetshard-sync/01-fleetshard-sync-secrets.yaml
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  fleetshard/config/config.go
  fleetshard/main.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/dbclient.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
  fleetshard/pkg/testutils/dbclient.go
  go.mod
Labels: lgtm, approved

#630 ROX-13561: Change Stage environment terraform CD from acs-stage-dp-01 to acs-stage-dp-02, supporting multi-AZ change.
  .github/workflows/deploy-stage.yaml
Labels: lgtm, approved

#631 Use production branch for observability resources
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#633 ROX-13693: Use Central-ID in database name
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#632 Bump stackrox version to 3.73.0
  dev/env/defaults/00-defaults.env
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#629 Add app-interface build CI embeddable status
  README.md
Labels: lgtm, approved

#635 Add quay user token when installing Operator from the upstream
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#637 Probe service: change default ProbeRunTimeout
  probe/config/config.go
Labels: lgtm, approved

#616 ROX-13262: Implement AWS auth for RDS
  dev/env/manifests/fleetshard-sync/01-fleetshard-sync-secrets.yaml
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  fleetshard/config/config.go
  fleetshard/config/config_test.go
  fleetshard/main.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
Labels: approved

#639 ROX-13396: Replace remaining occurrences of USE_AWS_VAULT.
  .github/workflows/deploy-production.yaml
  .github/workflows/deploy-stage.yaml
  .openshift-ci/e2e-runtime/docker_run_e2e.sh
Labels: lgtm, approved

#645 Rollback automatic tag resolution on prod
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#646 Rollback automatic tag resolution on prod (#645)
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#641 Use downstream version of the StackRox operator on stage
  CHANGELOG.md
  dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#627 ROX-13593: Add tenant ID as a k8s label
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm

#638 ROX-13756: Add managed DB parameters to the Helm chart
  CHANGELOG.md
  dp-terraform/helm/rhacs-terraform/Chart.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#649 Add AWS role arn parameter to the Helm chart
  dp-terraform/helm/rhacs-terraform/Chart.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#640 ROX-13737: Use built-in concurrency control.
  .github/workflows/deploy-production.yaml
  .github/workflows/deploy-stage.yaml
Labels: lgtm, approved

#636 ROX-13227: Fix negative DNS caching
  e2e/e2e_test.go
  internal/dinosaur/pkg/presenters/dinosaur.go
Labels: lgtm, approved

#651 ROX-13737: remove stale dependencies
  .github/workflows/deploy-production.yaml
  .github/workflows/deploy-stage.yaml
Labels: lgtm, approved

#652 ROX-13450: fix image check
  dp-terraform/helm/rhacs-terraform/check_image_exists.sh
Labels: approved

#643 ROX-13811: Enable Performance Insights for managed DBs
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  dp-terraform/helm/rhacs-terraform/Chart.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
  fleetshard/config/config.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Labels: lgtm, approved

#655 Improve RDS instance status log message
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Labels: approved

#656 ROX-13648: Revert "Rollback automatic tag resolution on prod (#645)"
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#657 Remove Openshift CI build root Dockerfile
  .openshift-ci/build-root/Dockerfile
Labels: lgtm, approved

#662 Release 2022 12 12.1.b7b15aa
  .github/workflows/deploy-production.yaml
  .github/workflows/deploy-stage.yaml
  .openshift-ci/build-root/Dockerfile
  CHANGELOG.md
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
  dp-terraform/helm/rhacs-terraform/Chart.yaml
  dp-terraform/helm/rhacs-terraform/check_image_exists.sh
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
  e2e/e2e_test.go
  fleetshard/config/config.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  internal/dinosaur/pkg/presenters/dinosaur.go
Labels: lgtm, approved

#663 Prepare CHANGELOG for the next release
  CHANGELOG.md
Labels: lgtm, approved

#634 ROX-12137: Use billing_marketplace_account instead of cloud_account_id
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
Labels: approved

#666 Increase operator container wait timeout on Openshift CI
  dev/env/scripts/bootstrap.sh
Labels: lgtm, approved

#665 ROX-12763: use claim mappings for admin:org:all role
  fleetshard/pkg/central/reconciler/init_auth.go
Labels: lgtm, approved

#669 Fix dnf metadata download errors on Openshift CI
  .openshift-ci/e2e-runtime/Dockerfile
Labels: approved

#670 Bump containerd version to 1.6.12
  dp-terraform/add-on/rhacs-terraform/go.mod
  dp-terraform/add-on/rhacs-terraform/go.sum
Labels: lgtm, approved

#671 Second attempt to upgrade containerd dependency
  dp-terraform/add-on/rhacs-terraform/go.mod
  dp-terraform/add-on/rhacs-terraform/go.sum
Labels: lgtm, approved

#672 ROX-13593: Add telemetry storage key to Centrals
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
  fleetshard/config/config.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
  go.mod
  go.sum
Labels: approved

#675 ROX-13106: Show hint to user when OCM user or org is not found
  internal/dinosaur/pkg/handlers/cloud_accounts.go
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  pkg/client/ocm/client.go
  pkg/errors/errors.go
Labels: lgtm

#677 ROX-13456: Use moq for DBClient
  .secrets.baseline
  fleetshard/pkg/central/cloudprovider/dbclient.go
  fleetshard/pkg/central/cloudprovider/dbclient_moq.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/testutils/dbclient.go
Labels: lgtm, approved

#676 Switch stage data plane to stage operator
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#667 ROX-12921: Introduce timeout for ACSCS requests
  .secrets.baseline
  Makefile
  internal/dinosaur/pkg/config/central.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/provisioning_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/timeout.go
  pkg/metrics/metrics.go
  templates/service-template.yml
Labels: approved

#686 Avoid using `which`
  Makefile
  dev/env/scripts/lib.sh
  dp-terraform/add-on/rhacs-terraform/Makefile
  pr_check_docker.sh
Labels: lgtm, approved

#688 Make `tools_venv` target depend on `tools/requirements.txt`
  Makefile
Labels: lgtm, approved

#678 ROX-13456: Refactor fleet-manager client in order to generate mocks for all kinds of APIs
  e2e/e2e_test.go
  pkg/client/fleetmanager/api_moq.go
  pkg/client/fleetmanager/client.go
  pkg/client/fleetmanager/client_mock.go
  pkg/client/fleetmanager/client_moq.go
  probe/internal/cli/cli.go
  probe/pkg/fleetmanager/client.go
  probe/pkg/probe/probe.go
  probe/pkg/probe/probe_test.go
Labels: lgtm, approved

#692 Fix: avoid panic on nil pointer
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_routes_cname_mgr.go
  pkg/client/aws/client.go
Labels: lgtm, approved

#700 ROX-13472: Mark parameters loaded from Parameter Store as read-only
  scripts/lib/external_config.sh
Labels: lgtm, approved

#690 ROX-12344: Use dev rhacs org_id in static token
  .secrets.baseline
  config/fleetshard-authz-org-ids-development.yaml
  config/static-token-payload.json
  dev/env/manifests/shared/03-configmap-config.yaml
  templates/service-template.yml
Labels: approved

#680 ROX-13911: Add RDS provisioning integration test
  .github/workflows/rds.yaml
  Makefile
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
Labels: lgtm, approved

#687 ROX-11993: Followup from review.
  README.md
  docs/architecture/README.md
Labels: lgtm, approved

#701 Fix dubious ownership error in CI
  .openshift-ci/e2e-runtime/Dockerfile
Labels: approved

#702 Update ACS operator to a Central version that includes Telemetry
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm

#679 ROX-13456: Bump detect-secrets to 1.4.0
  .pre-commit-config.yaml
  .secrets.baseline
  test/mocks/redhatsso.go
Labels: approved
