Repository stackrox/acs-fleet-manager, pull requests merged in 2022-06, with the labels that each got.

#136 Add OWNERS file
  OWNERS
Labels: lgtm

#139 ROX-11514: Add UID to the Grafana dashboard
  dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
Labels: lgtm, approved

#132 Allow configuring cloud provider and region of central request in e2e tests
  e2e/README.md
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
Labels: approved

#138 Add template params for data plane config file and providers
  config/dataplane-cluster-configuration-staging.yaml
  templates/service-template.yml
Labels: approved

#140 ROX-11413: Add central exposure route to central CR.
  fleetshard/pkg/centralreconciler/reconciler.go
  fleetshard/pkg/centralreconciler/reconciler_test.go
  fleetshard/pkg/k8s/client.go
  fleetshard/pkg/runtime/runtime.go
Labels: lgtm, approved

#131 Add RHSSO central OIDC secret to configuration and service-template.yml
  docs/feature-flags.md
  internal/dinosaur/pkg/config/dinosaur.go
  templates/service-template.yml
Labels: approved

#143 Add auth struct to private api: clientId, clientSecret etc.
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
  openapi/fleet-manager-private.yaml
Labels: lgtm, approved

#141 ROX-11467 - Add Central deletion e2e test
  e2e/README.md
  e2e/e2e_test.go
  fleetshard/pkg/fleetmanager/client.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/util.go
  internal/dinosaur/pkg/services/util_test.go
  scripts/setup-dev-env.sh
Labels: lgtm, approved

#146 pass through cert data to route
  fleetshard/pkg/centralreconciler/reconciler.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_endpoint.go
  internal/dinosaur/pkg/presenters/manageddinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  openapi/fleet-manager-private.yaml
Labels: approved

#156 Update OWNERS
  OWNERS
Labels: lgtm, approved

#147 Integrate pre-commit plugin detect-secrets
  .pre-commit-config.yaml
  .secrets.baseline
  CONTRIBUTING.md
  Makefile
Labels: lgtm, approved
