Repository stackrox/acs-fleet-manager, pull requests merged in 2023-02, with the labels that each got.

#777 Add dev build and deploy Make targets
  Makefile
  README.md
Labels: lgtm, approved

#780 ROX-14303: Disable telemetry for centrals created by probe service
  .secrets.baseline
  fleetshard/pkg/central/reconciler/reconciler.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_metadata.go
  internal/dinosaur/pkg/config/central.go
  internal/dinosaur/pkg/config/central_request.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/migrations/202301301200_add_internal_to_central_request.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/provisioning_dinosaurs_mgr.go
  internal/dinosaur/providers.go
  openapi/fleet-manager-private.yaml
  templates/service-template.yml
Labels: approved

#779 ROX-14650- Remove timeout log messages
  pkg/workers/reconciler.go
  pkg/workers/reconciler_test.go
Labels: lgtm, approved

#786 update observability operator to v4.0.4
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#789 Add namespace to kubectl calls
  Makefile
Labels: approved

#792 Remove add-on operator prototype
  dp-terraform/add-on/rhacs-terraform/.dockerignore
  dp-terraform/add-on/rhacs-terraform/.gitignore
  dp-terraform/add-on/rhacs-terraform/Dockerfile
  dp-terraform/add-on/rhacs-terraform/Makefile
  dp-terraform/add-on/rhacs-terraform/PROJECT
  dp-terraform/add-on/rhacs-terraform/README.md
  dp-terraform/add-on/rhacs-terraform/api/v1alpha1/terraform_types.go
  dp-terraform/add-on/rhacs-terraform/config/crd/bases/dataplane.acs.rhcloud.com_terraforms.yaml
  dp-terraform/add-on/rhacs-terraform/config/crd/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/default/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/default/manager_auth_proxy_patch.yaml
  dp-terraform/add-on/rhacs-terraform/config/default/manager_config_patch.yaml
  dp-terraform/add-on/rhacs-terraform/config/manager/controller_manager_config.yaml
  dp-terraform/add-on/rhacs-terraform/config/manager/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/manager/manager.yaml
  dp-terraform/add-on/rhacs-terraform/config/manifests/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/prometheus/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/prometheus/monitor.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/auth_proxy_client_clusterrole.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/auth_proxy_role.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/auth_proxy_role_binding.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/auth_proxy_service.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/leader_election_role.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/leader_election_role_binding.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/role.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/role_binding.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/service_account.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/terraform_editor_role.yaml
  dp-terraform/add-on/rhacs-terraform/config/rbac/terraform_viewer_role.yaml
  dp-terraform/add-on/rhacs-terraform/config/samples/dataplane_v1alpha1_terraform.yaml
  dp-terraform/add-on/rhacs-terraform/config/samples/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/scorecard/bases/config.yaml
  dp-terraform/add-on/rhacs-terraform/config/scorecard/kustomization.yaml
  dp-terraform/add-on/rhacs-terraform/config/scorecard/patches/basic.config.yaml
  dp-terraform/add-on/rhacs-terraform/config/scorecard/patches/olm.config.yaml
  dp-terraform/add-on/rhacs-terraform/go.mod
  dp-terraform/add-on/rhacs-terraform/go.sum
  dp-terraform/add-on/rhacs-terraform/hack/boilerplate.go.txt
  dp-terraform/add-on/rhacs-terraform/main.go
  dp-terraform/add-on/rhacs-terraform/pkg/terraform/values/translation/translation.go
  dp-terraform/add-on/rhacs-terraform/pkg/values/translation/utils.go
  dp-terraform/add-on/rhacs-terraform/pkg/values/translation/values_builder.go
  dp-terraform/add-on/rhacs-terraform/watches.yaml
Labels: lgtm, approved

#788 Revert "ROX-13456: Fail fast if cluster configuration is incorrect"
  fleetshard/pkg/runtime/runtime.go
  fleetshard/pkg/runtime/runtime_test.go
  pkg/client/fleetmanager/client.go
  pkg/client/fleetmanager/client_test.go
Labels: lgtm, approved

#790 Update ACS operator to include latest telemetry features
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm

#798 Allow DB instances to scale independently of each other
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Labels: lgtm, approved

#803 Fix internal user agents config in fleet manager template
  templates/service-template.yml
Labels: approved

#820 ROX-13913: change RDS CA certificate type
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Labels: lgtm, approved

#821 update prod observability operator to v4.0.4
  dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#819 stage central: v3.73.0-nightly-20230203 -> v3.74.0-nightly-20230213
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#806 Add operator install script
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/install_operator.sh
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#823 Skip tracking deletion for centrals from probe service
  internal/dinosaur/pkg/handlers/dinosaur.go
Labels: lgtm, approved

#743 ROX-14544 - Add CentralRequest field documentation
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
Labels: approved

#822 ROX-12462: add env annotations
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
  fleetshard/config/config.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
Labels: lgtm

#825 Use a released operator in stage, to test before ACSCS release.
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#824 ROX-12462: add env to fleetshard-sync, probe, cloudwatch-exporter
  deploy/helm/probe/deploy.sh
  deploy/helm/probe/templates/01-operator-04-deployment.yaml
  deploy/helm/probe/values.yaml
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-04-deployment.yaml
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#830 Use the same operator version in prod as stage.
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#839 ROX-14540: Dummy change to force building a new image.
  Makefile
Labels: lgtm, approved

#840 Build and push probe separately, and on production branch too.
  .github/workflows/ci.yaml
  .github/workflows/probe.yaml
Labels: lgtm, approved

#841 Build and push probe separately, and on production branch too. (#840)
  .github/workflows/ci.yaml
  .github/workflows/probe.yaml
Labels: lgtm, approved

#838 Fix RDS tests CI flake
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
Labels: lgtm, approved

#827 ROX-13913: Verify RDS certificates in Postgres connections
  Dockerfile
  Dockerfile.hybrid
  fleetshard/pkg/central/postgres/db_ca_certs.go
  fleetshard/pkg/central/postgres/dbconnection.go
  fleetshard/pkg/central/postgres/dbconnection_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#842 ROX-14955: Remove legacy Central DB migration step
  fleetshard/pkg/central/postgres/dbinit.go
Labels: lgtm, approved

#844 ROX-14540: Cherrypick a dummy `production` change onto `main`
  Makefile
Labels: approved
