Repository stackrox/acs-fleet-manager, pull requests merged in 2023-07, with the labels that each got.

#1137 Bump operator to v4.1.0
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1142 Release cherry-pick: Disable dog-fooding in prod (#1141)
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1146 Suppress chamber errors for secretsmanager backend
  scripts/lib/external_config.sh
Labels: lgtm, approved

#1151 ROX-17723: Add image pull secret for quay to Fleetshard-sync
  dp-terraform/helm/rhacs-terraform/templates/_helpers.tpl
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1152 ROX-17723: Fix imagePullSecret value source
  dp-terraform/helm/rhacs-terraform/templates/_helpers.tpl
Labels: lgtm, approved

#1153 ROX-18445: Move secured-cluster to dedicated namespace
  dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/_helpers.tpl
  dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-cr.yaml
  dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-secrets.yaml
Labels: lgtm, approved

#1154 ROX-18445: Create a namespace for secured cluster
  dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-namespace.yaml
Labels: lgtm, approved

#1145 Use unprivileged user in Dockerfile
  Dockerfile
  probe/Dockerfile
Labels: lgtm, approved

#1155 ROX-15791: Enable secured cluster by default
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1158 Add rds ca certs to unprivileged user
  Dockerfile
Labels: lgtm, approved

#1162 fix(probe): init probe metric gauges with zero value
  probe/cmd/probe/main.go
  probe/pkg/metrics/metrics.go
  probe/pkg/metrics/metrics_test.go
  probe/pkg/metrics/server.go
  probe/pkg/metrics/server_test.go
Labels: lgtm

#1166 chore(fleetshard): disable central-db PVC
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#1169 ROX-18427: tag RDS DBs with their corresponding ACS instance ID
  .secrets.baseline
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
  fleetshard/pkg/central/cloudprovider/dbclient.go
  fleetshard/pkg/central/cloudprovider/dbclient_moq.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#1176 Fix local bootstrap for RHACS_TARGETED_OPERATOR_UPGRADES mode
  dev/env/scripts/create-imagepullsecrets
  dev/env/scripts/docker.sh
  scripts/install_operator_canary.sh
Labels: lgtm, approved

#1150 Enforce security headers in Fleet Manager API
  templates/service-template.yml
Labels: lgtm, approved

#1177 Fix envoy response headers FM
  templates/service-template.yml
Labels: lgtm, approved

#1164 ROX-18428: add cipher package to fleetshard-sync
  fleetshard/pkg/cipher/cipher.go
  fleetshard/pkg/cipher/cipher_moq.go
  fleetshard/pkg/cipher/cipher_test.go
Labels: approved

#1103 ROX-17718: add operator labeling
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
  fleetshard/pkg/central/operator/upgrade.go
  fleetshard/pkg/central/operator/upgrade_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
  go.mod
  go.sum
Labels: lgtm, approved

#1041 ROX-16734: Reconcile Central Audit log notifier configuration
  dev/env/defaults/00-defaults.env
  fleetshard/config/config.go
  fleetshard/pkg/central/reconciler/proxy.go
  fleetshard/pkg/central/reconciler/proxy_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
  fleetshard/pkg/testutils/k8s.go
  go.mod
  go.sum
Labels: approved
