Repository stackrox/acs-fleet-manager, pull requests merged in 2023-03, with the labels that each got.

#858 Bump stackrox operator version to 3.74.0
  Dockerfile.hybrid
  dev/env/defaults/00-defaults.env
  dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#860 check that probe image exists before deployment
  deploy/helm/probe/deploy.sh
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  scripts/check_image_exists.sh
Labels: approved

#862 unquote the optional debug flags in probe deployment
  deploy/helm/probe/deploy.sh
Labels: lgtm, approved

#848 ROX-14696: Add terraforming and probe deployment to acs-stage-eu-01.
  .github/workflows/deploy-stage.yaml
Labels: approved

#882 expose instance type as label on Central pod
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_central.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  openapi/fleet-manager-private.yaml
Labels: lgtm

#874 ROX-14997: Add Secrets Manager support
  docs/development/secret-management.md
  docs/development/setup-osd-cluster-idp.md
  dp-terraform/osd-cluster-idp-setup.sh
  scripts/lib/external_config.sh
Labels: approved

#885 add grafana and prometheus rule label selectors
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
Labels: lgtm, approved

#886 Set ACS Operator CPU request and limit to 2
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Labels: lgtm, approved

#887 Revert "Set ACS Operator CPU request and limit to 2"
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Labels: lgtm, approved

#894 ROX-15922: update operator requests and limits
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Labels: lgtm, approved

#896 add AUTH_TYPE=OCM to fleetshard-sync in quickstart README
  README.md
Labels: lgtm, approved

#897 ROX-14997: Migrate dev scripts to Secrets Manager
  dev/env/scripts/exec_fleetshard_sync.sh
  dev/env/scripts/up.sh
  scripts/lib/external_config.sh
Labels: lgtm, approved

#900 ROX-16099: new DBs will use a LTS aurora-postgresql version
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Labels: lgtm, approved

#902 ROX-13952: Setup OIDC provider for the prod data plane cluster
  dp-terraform/osd-cluster-idp-setup.sh
Labels: lgtm, approved

#905 ROX-15806: Remove pause reconcile annotation before Central deletion
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#903 ROX-16108: Remove Targeted Cluster Placement Strategy
  internal/dinosaur/pkg/config/dataplane_cluster_config.go
  internal/dinosaur/pkg/services/cluster_placement_strategy.go
  internal/dinosaur/pkg/services/cluster_placement_strategy_test.go
Labels: lgtm, approved

#872 Add org name as label to namespace and Central CR
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: approved

#898 ROX-12188: central default version api for canary upgrades
  cmd/fleet-manager/main_test.go
  config/admin-authz-roles-dev.yaml
  config/admin-authz-roles-prod.yaml
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/api_default.go
  internal/dinosaur/pkg/api/admin/private/model_central_default_version.go
  internal/dinosaur/pkg/api/dbapi/central_default_version.go
  internal/dinosaur/pkg/config/central.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/migrations/20230321000000_add_central_default_version.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/central_default_version.go
  internal/dinosaur/pkg/services/central_default_version_moq.go
  internal/dinosaur/pkg/services/central_default_version_test.go
  openapi/fleet-manager-private-admin.yaml
  pkg/providers/core.go
Labels: approved

#908 Release 2023-03-28.1.4ee6131
  README.md
  dev/env/scripts/exec_fleetshard_sync.sh
  dev/env/scripts/up.sh
  docs/development/secret-management.md
  docs/development/setup-osd-cluster-idp.md
  dp-terraform/helm/rhacs-terraform/charts/logging/README.md
  dp-terraform/helm/rhacs-terraform/charts/logging/crds/logging.yaml
  dp-terraform/helm/rhacs-terraform/charts/observability/README.md
  dp-terraform/helm/rhacs-terraform/charts/observability/crds/observability.yaml
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
  dp-terraform/osd-cluster-idp-setup.sh
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  go.mod
  go.sum
  internal/dinosaur/pkg/config/dataplane_cluster_config.go
  internal/dinosaur/pkg/services/cluster_placement_strategy.go
  internal/dinosaur/pkg/services/cluster_placement_strategy_test.go
  internal/dinosaur/pkg/services/telemetry.go
  pkg/client/telemetry/config.go
  pkg/client/telemetry/telemeter_moq.go
  scripts/lib/external_config.sh
Labels: lgtm, approved

#910 use annotation for org name instead of label
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved
