Repository stackrox/acs-fleet-manager, pull requests merged in 2023-10, with the labels that each got.

#1308 ROX-19811: Set label selector to dogfooding secured cluster CR
  dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-cr.yaml
Labels: approved

#1303 Load image into kind automatically
  Makefile
Labels: lgtm, approved

#1316 ROX-18908: Hook up integration to dogfood central.
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1317 Fixes local development for gitops feature
  dev/env/defaults/00-defaults.env
  dev/env/manifests/fleet-manager/04-gitops-config.yaml
  dev/env/manifests/rhacs-operator/03-operators-config.yaml
  dev/env/scripts/create-imagepullsecrets
  dev/env/scripts/docker.sh
  dev/env/scripts/lib.sh
  fleetshard/pkg/central/operator/upgrade.go
  scripts/deploy_operator_canary.sh
  scripts/install_operator_canary.sh
Labels: approved

#1318 ROX-19841: Remove unused target
  Makefile
Labels: lgtm, approved

#1296 ROX-16664: backup central encryption key
  e2e/e2e_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/k8s/secret.go
Labels: lgtm, approved

#1319 ROX-19994: Drop RHACS_STANDALONE_MODE feature flag
  dev/env/manifests/rhacs-operator/03-operators-config.yaml
  e2e/e2e_canary_upgrade_test.go
  fleetshard/pkg/central/operator/upgrade.go
  fleetshard/pkg/runtime/runtime.go
  pkg/features/list.go
Labels: lgtm, approved

#1323 Fix log message about injecting image pull secrets into service account
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#1322 Fix path typo in e2e documentation
  docs/development/setup-test-environment.md
Labels: lgtm, approved

#1320 ROX-16669: Update Stackrox version
  dev/env/manifests/crds/01-platform.stackrox.io_centrals.yaml
  dev/env/manifests/crds/02-platform.stackrox.io_securedclusters.yaml
  go.mod
  go.sum
Labels: lgtm, approved

#1328 ROX-20053: Set controller-runtime logger
  fleetshard/main.go
  pkg/logger/kubeapi_logger.go
Labels: lgtm, approved

#1332 ROX-19904: Introduce the addon script to deploy the data plane with OCM
  dp-terraform/ocm/install_addon.sh
Labels: approved

#1330 dev scripts: Add delay before patching ServiceAccounts to include Image Pull Secrets
  dev/env/scripts/install_operator.sh
Labels: approved

#1321 Move auth and client init into BeforeEach to improve Ginkgo errors
  e2e/e2e_canary_upgrade_test.go
Labels: lgtm, approved

#1335 ROX-20110: Update operator helm chart documentation
  fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
Labels: lgtm, approved

#1331 Fix scanner version for e2e tests
  dev/env/defaults/00-defaults.env
  docs/development/setup-test-environment.md
Labels: lgtm, approved

#1334 ROX-13622: dev env: Update Ginkgo CLI invocation to not use deprecated option
  Makefile
Labels: lgtm, approved

#1337 bump golang.org/x/net from 0.15.0 to 0.17.0
  go.mod
  go.sum
Labels: lgtm, approved

#1338 fix ForceReconcile, add unit and e2e tests
  e2e/e2e_test.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/admin_dinosaur_test.go
Labels: lgtm, approved

#1344 ROX-20147: Fix invalid egress-proxy manifest
  fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
Labels: approved

#1349 Remove flag to specify gitops config path
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/scripts/lib.sh
  internal/dinosaur/pkg/gitops/const.go
  internal/dinosaur/pkg/gitops/module.go
  internal/dinosaur/pkg/gitops/provider.go
  pkg/providers/core.go
  templates/service-template.yml
Labels: lgtm, approved

#1351 ROX-19904: Add addon version and fleetshardImageTag parameter
  dp-terraform/ocm/install_addon.sh
Labels: lgtm, approved

#1339 ROX-20144: Move canary e2e to gitops
  dev/env/manifests/fleet-manager/04-gitops-config.yaml
  dev/env/scripts/reset
  e2e/e2e_canary_upgrade_test.go
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
Labels: approved

#1355 Update e2e.sh
  .openshift-ci/tests/e2e.sh
Labels: lgtm, approved

#1353 Update GitHub handle in OWNERS file
  OWNERS
Labels: lgtm, approved

#1356 add lcleroux to OWNERS
  OWNERS
Labels: lgtm, approved

#1358 Fix precommit for flag fitops
  .openshift-ci/tests/e2e.sh
Labels: approved

#1340 ROX-19846: Use roxbot account to create PRs.
  .github/workflows/create-prod-pr.yaml
  .github/workflows/start-release.yaml
Labels: lgtm, approved

#1360 Validate central patch better
  internal/dinosaur/pkg/gitops/config.go
  internal/dinosaur/pkg/gitops/config_test.go
  internal/dinosaur/pkg/gitops/service.go
Labels: lgtm, approved

#1347 add e2e test for secret restore
  e2e/e2e_test.go
Labels: lgtm, approved

#1372 add configmap watch
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleet-manager/05-fleet-manager-rbac.yaml
  internal/dinosaur/pkg/gitops/provider.go
  internal/dinosaur/pkg/gitops/reader.go
  internal/dinosaur/providers.go
Labels: lgtm, approved

#1369 explicit config for canary e2e
  e2e/e2e_canary_upgrade_test.go
Labels: lgtm, approved

#1374 Lc/decrease poll period
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
Labels: lgtm, approved

#1350 Do not inject feature flag defaults into Kubernetes Deployments
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#1378 ROX-19904: Add OCM cluster id override
  dp-terraform/ocm/install_addon.sh
Labels: lgtm, approved

#1387 ROX-20130: update gRPC to v1.58.3
  go.mod
  go.sum
Labels: lgtm, approved

#1385 Enable GitOps feature by default
  .openshift-ci/e2e-runtime/Dockerfile
  .openshift-ci/tests/e2e-test.sh
  .openshift-ci/tests/e2e.sh
  dev/env/defaults/00-defaults.env
  dev/env/defaults/10-operator-source.env
  dev/env/defaults/cluster-type-colima/env
  dev/env/defaults/cluster-type-docker/env
  dev/env/defaults/cluster-type-kind/env
  dev/env/defaults/cluster-type-minikube/env
  dev/env/defaults/cluster-type-rancher-desktop/env
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleet-manager/04-gitops-config.yaml
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/create-imagepullsecrets
  dev/env/scripts/docker.sh
  dev/env/scripts/down.sh
  dev/env/scripts/ensure_operator_image_exists.sh
  dev/env/scripts/install_operator.sh
  dev/env/scripts/lib.sh
  dev/env/scripts/reset
  dev/env/scripts/up.sh
  e2e/e2e_auth_test.go
  e2e/e2e_canary_upgrade_test.go
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
  fleetshard/pkg/central/operator/config.go
  fleetshard/pkg/central/operator/upgrade.go
  fleetshard/pkg/central/operator/upgrade_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/runtime/runtime.go
Labels: lgtm, approved

#1343 ROX-20146: Remove rhacs-operator subscription in integration
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1403 ROX-20350 enable gitops on integration (fleetshard)
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1394 Escape linebreaks in json
  dp-terraform/ocm/install_addon.sh
Labels: approved

#1404 Add tests for default central template
  internal/dinosaur/pkg/gitops/config.go
  internal/dinosaur/pkg/gitops/default_central.yaml
  internal/dinosaur/pkg/gitops/default_central_test.go
Labels: lgtm, approved

#1393 Remove 30m sleep on e2e failure
  .openshift-ci/tests/e2e-test.sh
Labels: lgtm, approved

#1405 Enable gitops on fleetshard on stage
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#1408 Disable operator on stage and prod
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1411 Update squid proxy image
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm

#1413 chore: bump cloudwatch exporter to v0.55.0
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
Labels: lgtm, approved

#1412 Fix pause reconcile annotation
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#1247 Improve AMS error experience
  pkg/errors/errors.go
Labels: lgtm, approved

#1418 ROX-18504: GitOps Cleanup
  .secrets.baseline
  cmd/fleet-manager/main_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/api_default.go
  internal/dinosaur/pkg/api/admin/private/model_central.go
  internal/dinosaur/pkg/api/admin/private/model_central_default_version.go
  internal/dinosaur/pkg/api/admin/private/model_central_request_payload.go
  internal/dinosaur/pkg/api/admin/private/model_central_spec.go
  internal/dinosaur/pkg/api/admin/private/model_central_update_request.go
  internal/dinosaur/pkg/api/admin/private/model_resource_requirements.go
  internal/dinosaur/pkg/api/admin/private/model_scanner_spec.go
  internal/dinosaur/pkg/api/admin/private/model_scanner_spec_analyzer.go
  internal/dinosaur/pkg/api/admin/private/model_scanner_spec_analyzer_scaling.go
  internal/dinosaur/pkg/api/admin/private/model_scanner_spec_db.go
  internal/dinosaur/pkg/api/dbapi/central_default_version.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_central.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_scanner.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_scanner_analyzer.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_scanner_analyzer_scaling.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_scanner_db.go
  internal/dinosaur/pkg/api/private/model_resource_requirements.go
  internal/dinosaur/pkg/api/public/api/openapi.yaml
  internal/dinosaur/pkg/api/public/model_central_request_payload.go
  internal/dinosaur/pkg/api/public/model_central_spec.go
  internal/dinosaur/pkg/api/public/model_resource_requirements.go
  internal/dinosaur/pkg/api/public/model_scanner_spec.go
  internal/dinosaur/pkg/api/public/model_scanner_spec_analyzer.go
  internal/dinosaur/pkg/api/public/model_scanner_spec_analyzer_scaling.go
  internal/dinosaur/pkg/api/public/model_scanner_spec_db.go
  internal/dinosaur/pkg/config/central.go
  internal/dinosaur/pkg/converters/resourceutil.go
  internal/dinosaur/pkg/converters/resourceutil_test.go
  internal/dinosaur/pkg/generated/bindata.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/admin_dinosaur_test.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/migrations/20230616000000_add_acs_operator_version.go
  internal/dinosaur/pkg/migrations/20231026000000_remove_overrides.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/admin_dinosaur.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/central_default_version.go
  internal/dinosaur/pkg/services/central_default_version_moq.go
  internal/dinosaur/pkg/services/central_default_version_test.go
  internal/dinosaur/pkg/services/dinosaur.go
  openapi/fleet-manager-private-admin.yaml
  openapi/fleet-manager-private.yaml
  openapi/fleet-manager.yaml
  pkg/client/fleetmanager/api_moq.go
  pkg/client/fleetmanager/client.go
  pkg/providers/core.go
Labels: lgtm, approved

#1425 ROX-20542: disable http/2 in operator kube-rbac-proxy to mitigate CVE-2023-44487
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
Labels: lgtm, approved
