Repository stackrox/acs-fleet-manager, pull requests merged in 2023-01, with the labels that each got.

#717 Bump stage Central version to nightly-2023-01-09 build
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#719 Bump stage Central version to nightly-2023-01-10 build
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#689 ROX-13408: Use api.iam.clients in dynamic clients API wrapper
  pkg/client/redhatsso/dynamicclients/client.go
Labels: lgtm, approved

#722 ROX-13666: Refactor DB connection string
  .secrets.baseline
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/dbclient.go
  fleetshard/pkg/central/cloudprovider/dbclient_moq.go
  fleetshard/pkg/central/postgres/postgres.go
  fleetshard/pkg/central/postgres/postgres_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#720 ROX-12921: initialize counter metrics with 0 value
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_routes_cname_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/provisioning_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/ready_dinosaurs_mgr.go
  pkg/metrics/metrics.go
Labels: lgtm, approved

#683 ROX-12344: Add organisation name to central request
  Makefile
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
  internal/dinosaur/pkg/handlers/cloud_accounts.go
  internal/dinosaur/pkg/handlers/cloud_accounts_test.go
  internal/dinosaur/pkg/migrations/202212150000_add_organisation_name.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
  openapi/fleet-manager-private.yaml
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
  pkg/errors/errors.go
  templates/service-template.yml
Labels: lgtm, approved, ok-to-test

#735 Bump operator version to 3.73.1 on prod
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#737 Bump operator to 3.73.1 in test environment
  dev/env/defaults/00-defaults.env
  dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
Labels: approved

#736 Revert "ROX-12344: Add organisation name to central request"
  Makefile
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
  internal/dinosaur/pkg/handlers/cloud_accounts.go
  internal/dinosaur/pkg/handlers/cloud_accounts_test.go
  internal/dinosaur/pkg/migrations/202212150000_add_organisation_name.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
  openapi/fleet-manager-private.yaml
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
  pkg/errors/errors.go
  templates/service-template.yml
Labels: approved

#738 Update changelog for the 2023-01-17.1.f4e71a7 release
  CHANGELOG.md
Labels: approved

#721 ROX-12486: Add support for using existing log groups created by terraform
  CHANGELOG.md
  dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-log-forwarder.yaml
  dp-terraform/helm/rhacs-terraform/charts/logging/values.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#734 Increase OCM token margin for refresh
  pkg/client/fleetmanager/auth_ocm.go
Labels: lgtm, approved

#742 ROX-13666: Split dbclient.EnsureDBProvisioned() into two functions
  .secrets.baseline
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
  fleetshard/pkg/central/cloudprovider/dbclient.go
  fleetshard/pkg/central/cloudprovider/dbclient_moq.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#740 Revert "Revert "ROX-12344: Add organisation name to central request""
  Makefile
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
  internal/dinosaur/pkg/handlers/cloud_accounts.go
  internal/dinosaur/pkg/handlers/cloud_accounts_test.go
  internal/dinosaur/pkg/migrations/202212150000_add_organisation_name.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
  openapi/fleet-manager-private.yaml
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
  pkg/errors/errors.go
  templates/service-template.yml
Labels: lgtm, approved

#684 ROX-12344: Add org-id label and org-name annotation
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: approved, ok-to-test

#733 Rox 13593: Add telemetry service
  .secrets.baseline
  cmd/fleet-manager/main_test.go
  go.mod
  go.sum
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/telemetry.go
  pkg/client/telemetry/config.go
  pkg/errors/errors.go
  pkg/providers/core.go
  templates/service-template.yml
Labels: lgtm, approved

#749 Increase RDS integration tests timeout
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
Labels: lgtm, approved

#745 Make org name migration more robust
  internal/dinosaur/pkg/migrations/202212150000_add_organisation_name.go
Labels: lgtm, approved

#746 ROX-13593: Use account id as user in track events
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/services/telemetry.go
Labels: approved

#747 ROX-13593: Store telemetry storage key as secret
  .secrets.baseline
  pkg/client/telemetry/config.go
  templates/service-template.yml
Labels: approved

#751 ROX-14473: require user org_id to match ACS owner org_id
  fleetshard/pkg/central/reconciler/init_auth.go
Labels: lgtm, approved

#760 Release 2023 01 24.1.e67c2c6
  .secrets.baseline
  CHANGELOG.md
  Makefile
  cmd/fleet-manager/main_test.go
  dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-log-forwarder.yaml
  dp-terraform/helm/rhacs-terraform/charts/logging/values.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
  fleetshard/pkg/central/cloudprovider/dbclient.go
  fleetshard/pkg/central/cloudprovider/dbclient_moq.go
  fleetshard/pkg/central/reconciler/init_auth.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  go.mod
  go.sum
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/cloud_accounts.go
  internal/dinosaur/pkg/handlers/cloud_accounts_test.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/migrations/202212150000_add_organisation_name.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
  internal/dinosaur/pkg/services/telemetry.go
  openapi/fleet-manager-private.yaml
  pkg/client/fleetmanager/auth_ocm.go
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
  pkg/client/telemetry/config.go
  pkg/errors/errors.go
  pkg/providers/core.go
  probe/Dockerfile
  templates/service-template.yml
  tools/go.mod
  tools/go.sum
Labels: lgtm, approved

#759 git ignore all secret files
  .gitignore
Labels: lgtm, approved

#764 ROX-13924: provision failover RDS instance
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
Labels: lgtm, approved

#763 ROX-13593: Use `user_id` and `rh-user-id` claims in telemetry events
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/services/telemetry.go
  pkg/auth/acs_claims.go
  pkg/auth/acs_claims_test.go
  pkg/auth/context_config.go
  pkg/auth/context_test.go
Labels: approved

#766 Add documentation to AuthConfig fields.
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
Labels: lgtm, approved

#769 ROX-14522: Switch managed DB params from application specific to cluster specific
  .github/workflows/rds.yaml
  dev/env/scripts/exec_fleetshard_sync.sh
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  fleetshard/README.md
Labels: lgtm, approved

#768 Remove CHANGELOG.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: lgtm, approved

#770 fix error in telemetry track events
  internal/dinosaur/pkg/services/telemetry.go
  internal/dinosaur/pkg/services/telemetry_moq.go
  internal/dinosaur/pkg/services/telemetry_test.go
  pkg/client/telemetry/config.go
  pkg/client/telemetry/config_moq.go
  pkg/client/telemetry/telemeter_moq.go
  pkg/providers/core.go
Labels: lgtm

#762 ROX-14649 - Clean-up acs-fleet-manager logs
  internal/dinosaur/pkg/workers/clusters_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_routes_cname_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/provisioning_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/ready_dinosaurs_mgr.go
  pkg/handlers/framework.go
  pkg/logger/logger.go
  pkg/server/logging/writer.go
Labels: lgtm, approved

#783 Release 2023-01-31.1.ad850f3
  .github/pull_request_template.md
  .github/workflows/rds.yaml
  .gitignore
  CHANGELOG.md
  dev/env/scripts/exec_fleetshard_sync.sh
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  fleetshard/README.md
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/services/telemetry.go
  internal/dinosaur/pkg/services/telemetry_moq.go
  internal/dinosaur/pkg/services/telemetry_test.go
  pkg/auth/acs_claims.go
  pkg/auth/acs_claims_test.go
  pkg/auth/context_config.go
  pkg/auth/context_test.go
  pkg/client/telemetry/config.go
  pkg/client/telemetry/config_moq.go
  pkg/client/telemetry/telemeter_moq.go
  pkg/providers/core.go
Labels: lgtm, approved

#767 Provide utility to disable/enable admin password for specific central CR
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/util/revision.go
  fleetshard/pkg/util/revision_test.go
  pkg/shared/central_admin_password.go
Labels: approved
