Repository stackrox/acs-fleet-manager, pull requests merged in 2023-08, with the labels that each got.

#1183 ROX-14547: Configure audit logs to use proper region
  dp-terraform/helm/rhacs-terraform/charts/audit-logs/values.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1156 ROX-17335: Reconcile auth provider + groups declaratively.
  dev/config/dataplane-cluster-configuration-rancherdesktop.yaml
  fleetshard/pkg/central/client/client.go
  fleetshard/pkg/central/reconciler/init_auth.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/central/reconciler/util.go
Labels: approved

#1178 ROX-18428: implement KMS encryption and decryption
  .github/workflows/aws-integration.yaml
  Makefile
  dev/env/scripts/exec_fleetshard_sync.sh
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
  fleetshard/pkg/cipher/aes256_cipher.go
  fleetshard/pkg/cipher/aes256_cipher_test.go
  fleetshard/pkg/cipher/cipher.go
  fleetshard/pkg/cipher/kms_cipher.go
  fleetshard/pkg/cipher/kms_cipher_test.go
Labels: approved

#1188 ROX-17260: Add annotation to trigger yearly certificate rotation
  dp-terraform/helm/rhacs-terraform/charts/audit-logs/templates/06-statefulset.yaml
Labels: lgtm, approved

#1179 ROX-18728: Add operator deployment cache
  fleetshard/pkg/runtime/runtime.go
Labels: approved

#1192 Fix deploy/bootstrap make target
  dev/env/defaults/00-defaults.env
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#1199 Update alertmanager grouping confiugration
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-alertmanager.yaml
Labels: lgtm

#1203 Changing labels to group by
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-03-secret-alertmanager.yaml
Labels: lgtm

#1200 Add k8s API to NO_PROXY configuration
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: approved

#1205 fix(reconciler): make default group not declarative
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#1206 Release 2023-08-16.1.26e46dd
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#1212 feat(terraform): add acsOperator repository value
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1213 fix(fleetshard): set Central PVC annotation only if managedDB=true
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: approved

#1190 ROX-16090: Start data plane CD on integration environment.
  .github/workflows/deploy-integration.yaml
  docs/development/setup-osd-cluster-idp.md
  dp-terraform/cd-robot-account-setup.sh
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/osd-cluster-idp-setup.sh
Labels: lgtm, approved

#1215 ROX-16090: Support integration in a couple more places
  deploy/helm/probe/deploy.sh
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1223 ROX-19330: Add second declarative config mount point to central CR
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#1224 fix(fleet-manager): add nil check to deleting mgr
  internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go
Labels: lgtm

#1185 ROX-18428: report secret data to fleet-manager
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
  fleetshard/config/config.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/cipher/cipher.go
  fleetshard/pkg/cipher/local_base64_cipher.go
  fleetshard/pkg/cipher/local_base64_cipher_test.go
  fleetshard/pkg/k8s/route.go
  fleetshard/pkg/k8s/secret.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/dbapi/data_plane_central_status.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_data_plane_central_status.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_metadata.go
  internal/dinosaur/pkg/migrations/20230802000000_add_secrets_field_to_central_request.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/data_plane_dinosaur_status.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/data_plane_dinosaur.go
  openapi/fleet-manager-private.yaml
Labels: approved

#1227 Release 2023-08-29.1.63189b2
  .github/workflows/deploy-integration.yaml
  deploy/helm/probe/deploy.sh
  docs/development/setup-osd-cluster-idp.md
  dp-terraform/cd-robot-account-setup.sh
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
  dp-terraform/osd-cluster-idp-setup.sh
  fleetshard/config/config.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/cipher/cipher.go
  fleetshard/pkg/cipher/local_base64_cipher.go
  fleetshard/pkg/cipher/local_base64_cipher_test.go
  fleetshard/pkg/k8s/route.go
  fleetshard/pkg/k8s/secret.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/dbapi/data_plane_central_status.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_data_plane_central_status.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_metadata.go
  internal/dinosaur/pkg/migrations/20230802000000_add_secrets_field_to_central_request.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/data_plane_dinosaur_status.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/data_plane_dinosaur.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/deleting_dinosaurs_mgr.go
  openapi/fleet-manager-private.yaml
Labels: lgtm, approved

#1228 ROX-19478: Parameterize manager RDS secret name.
  .secrets.baseline
  templates/service-template.yml
Labels: lgtm, approved
