Repository stackrox/acs-fleet-manager, pull requests merged in 2023-12, with the labels that each got.

#1518 Adjust egress proxy resources and replicas
  e2e/e2e_test.go
  fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
  fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
Labels: lgtm, approved

#1519 ROX-20025: Add Gitops dev doc
  README.md
  docs/development/gitops-configure-central-and-operator.md
Labels: lgtm, approved

#1528 Add expiration date worker lease via migrations
  internal/dinosaur/pkg/migrations/20231212140000_add_expiration_lease_type.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/expiration_date_mgr.go
  internal/dinosaur/providers.go
Labels: approved

#1464 Drop image preload for local setup
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/docker.sh
Labels: approved

#1527 chore(dashboards): cover new cluster names in data sources regex
  dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
  dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
Labels: lgtm, approved

#1503 ROX-21070: Add fleetshard addon installation status to private api
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/central/reconciler/status.go
  internal/dinosaur/pkg/api/dbapi/data_plane_cluster_status.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_data_plane_central_status.go
  internal/dinosaur/pkg/api/private/model_data_plane_central_status_conditions.go
  internal/dinosaur/pkg/api/private/model_data_plane_cluster_update_status_request.go
  internal/dinosaur/pkg/api/private/model_data_plane_cluster_update_status_request_addons.go
  internal/dinosaur/pkg/handlers/data_plane_cluster.go
  internal/dinosaur/pkg/migrations/20231123000000_add_cluster_addons.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/data_plane_cluster_status.go
  internal/dinosaur/pkg/services/data_plane_cluster.go
  internal/dinosaur/test/integration/data_plane_endpoints_test.go
  openapi/fleet-manager-private.yaml
  pkg/api/cluster_types.go
Labels: lgtm, approved

#1539 fix: central expired-at method
  internal/dinosaur/pkg/routes/route_loader.go
Labels: lgtm

#1504 ROX-21070: Publish addon state from fleetshard-sync
  dev/env/manifests/addons/00-addon-crd.yaml
  dev/env/manifests/addons/01-acs-fleetshard-addon.yaml
  dev/env/manifests/addons/02-acs-fleetshard-parameters-secret.yaml
  dev/env/scripts/bootstrap.sh
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
  fleetshard/config/config.go
  fleetshard/pkg/cluster/addon_service.go
  fleetshard/pkg/cluster/addon_service_test.go
  fleetshard/pkg/k8s/client.go
  fleetshard/pkg/runtime/runtime.go
  fleetshard/pkg/testutils/k8s.go
  go.mod
  go.sum
  pkg/client/fleetmanager/api_moq.go
  pkg/client/fleetmanager/client.go
  pkg/features/list.go
  pkg/shared/addon.go
  pkg/shared/addon_test.go
Labels: approved

#1521 ROX-21070: Declare Data Plane Cluster configuration in gitops config
  internal/dinosaur/pkg/gitops/config.go
  internal/dinosaur/pkg/gitops/config_test.go
  internal/dinosaur/pkg/gitops/provider_test.go
Labels: lgtm, approved
