Repository stackrox/acs-fleet-manager, pull requests merged in 2023-04, with the labels that each got.

#914 Change RDS DB CA certificate type
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Labels: lgtm, approved

#912 Pass the region from the parameter store to the fleetshard sync
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#916 Add missing AWS_ROLE_ARN parameter in dev script for fleetshard-sync
  dev/env/scripts/exec_fleetshard_sync.sh
  dev/env/scripts/up.sh
Labels: approved

#923 Bugfix-release 2023-04-04.1.1c8acf5
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Labels: lgtm, approved

#928 import rpm gpg key for CentOS
  .openshift-ci/e2e-runtime/Dockerfile
Labels: lgtm, approved

#871 ROX-15155: Add ACS Operator install/upgrade from Fleetshard-sync
  fleetshard/config/config.go
  fleetshard/config/config_test.go
  fleetshard/pkg/central/charts/data/rhacs-operator/Chart.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/platform.stackrox.io_centrals.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/platform.stackrox.io_securedclusters.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-controller-manager-metrics-service_v1_service.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-service-account.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
  fleetshard/pkg/central/operator/upgrade.go
  fleetshard/pkg/central/operator/upgrade_test.go
  fleetshard/pkg/runtime/runtime.go
Labels: lgtm, approved

#924 use HEAD as tag for fleetshard-sync image
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: approved

#929 Bugfix-release 2023-04-04.2.1c8acf5
  .openshift-ci/e2e-runtime/Dockerfile
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#931 use HEAD as tag for probe image
  deploy/helm/probe/deploy.sh
Labels: lgtm, approved

#930 ROX-16355: Fix github action issues for contributors
  .github/workflows/ci.yaml
  .github/workflows/pre-commit.yaml
  .github/workflows/rds.yaml
Labels: approved

#933 Bugfix-release 2023-04-04.3.2d936a1
  deploy/helm/probe/deploy.sh
Labels: lgtm, approved

#925 Help future generations with BitWarden CLI errors.
  docs/development/secret-management.md
  fleetshard/README.md
Labels: lgtm, approved

#934 ROX-16355: Do not run RDS tests from forks
  .github/workflows/rds.yaml
Labels: lgtm, approved

#906 MGDX-396 Upgraded app-services-sdk-go to Core SDK
  go.mod
  go.sum
  pkg/client/redhatsso/serviceaccounts/client.go
  pkg/client/redhatsso/serviceaccounts/client_test.go
  pkg/client/redhatsso/serviceaccounts/integration/client_test.go
  pkg/services/sso/redhatsso_service.go
  test/mocks/redhatsso.go
Labels: lgtm, approved, ok-to-test

#857 ROX-15136: filter aws metrics by cluster name
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-04-deployment.yaml
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
Labels: lgtm

#945 ROX-16280: Terraform acs-stage-eu-02 on CI
  .github/workflows/deploy-stage.yaml
Labels: lgtm, approved

#947 ROX-15355: Remove HTPasswd creation
  docs/development/setup-osd-cluster-idp.md
  dp-terraform/osd-cluster-idp-setup.sh
Labels: lgtm, approved

#932 ROX-16362: Terraform acs-prod-eu-01 on CI
  .github/workflows/deploy-production.yaml
Labels: lgtm, approved

#946 expand cloudwatch exports to eu region
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
Labels: lgtm, approved

#948 bump observability operator to v4.2.1
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#911 ROX-13092: Add openshift eventrouter to persist kubernetes events to CloudWatch
  dp-terraform/helm/rhacs-terraform/charts/logging/README.md
  dp-terraform/helm/rhacs-terraform/charts/logging/templates/02-eventrouter-01-rbac.yaml
  dp-terraform/helm/rhacs-terraform/charts/logging/templates/02-eventrouter-02-configmap.yaml
  dp-terraform/helm/rhacs-terraform/charts/logging/templates/02-eventrouter-03-deployment.yaml
Labels: lgtm

#949 ROX-14030: use new availability SLI rules in dashboard
  dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
Labels: lgtm, approved

#952 use new SLI recording rule also in history panel
  dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
Labels: lgtm, approved

#953 ROX-15354: deploy probe service to EU data plane clusters
  .github/workflows/deploy-data-plane.yaml
  .github/workflows/deploy-production.yaml
  .github/workflows/deploy-stage.yaml
  deploy/helm/probe/deploy.sh
  deploy/helm/probe/templates/01-operator-04-deployment.yaml
  deploy/helm/probe/values.yaml
Labels: lgtm, approved

#955 ROX-15354: fix probe deployment to multiple US/EU clusters
  .github/workflows/deploy-data-plane.yaml
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-production.yaml
  .github/workflows/deploy-stage.yaml
Labels: lgtm, approved

#943 ROX-16338 Add central label selector to operator helm chart
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
Labels: lgtm, approved

#963 Hardcode Fleet-Manager CLI command registration
  cmd/fleet-manager/main.go
  internal/dinosaur/providers.go
  pkg/providers/core.go
Labels: lgtm, approved

#964 ROX-16153: Switch channel from latest to the specific minor version in openshift CI
  dev/env/defaults/00-defaults.env
  dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
  dev/env/manifests/rhacs-operator/quay/03-subscription.yaml
  dev/env/scripts/lib.sh
Labels: approved

#909 ROX-16205: Add Operator Version label to Centrals
  fleetshard/main.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
Labels: lgtm, approved

#965 improve probe logging
  probe/pkg/probe/probe.go
Labels: lgtm, approved

#966 Remove unsupported CLI commands
  cmd/fleet-manager/main.go
Labels: approved

#967 add region label to probe metrics
  probe/pkg/metrics/metrics.go
  probe/pkg/metrics/metrics_test.go
  probe/pkg/metrics/server_test.go
  probe/pkg/probe/probe.go
  probe/pkg/runtime/runtime.go
Labels: lgtm, approved

#969 Update pull_request_template.md
  .github/pull_request_template.md
Labels: lgtm, approved

#973 Add response logging to probe service
  probe/pkg/probe/probe.go
Labels: lgtm, approved

#968 send actual and desired version to fleetshard in private API
  fleetshard/pkg/central/reconciler/reconciler.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_versions.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  openapi/fleet-manager-private.yaml
Labels: lgtm, approved

#974 Disable OCM logger by default
  pkg/client/fleetmanager/auth.go
  pkg/client/fleetmanager/auth_ocm.go
Labels: lgtm, approved

#971 ROX-16500 cloud region display names
  internal/dinosaur/pkg/clusters/standalone_provider.go
  internal/dinosaur/pkg/wellknown/cloud_regions.go
  internal/dinosaur/pkg/wellknown/cloud_regions_test.go
  internal/dinosaur/pkg/wellknown/doc.go
Labels: lgtm, approved

#975 Remove development environment log message
  pkg/environments/environment.go
Labels: lgtm, approved

#785 ROX-15242 - Reduce fleetshard and fleet-manager log noise
  Makefile
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/ready_dinosaurs_mgr.go
  pkg/logger/logger.go
Labels: approved

#981 Bump operator to v4.0.0 on stage
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#982 Use stable subscription channel
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Labels: lgtm, approved

#983 Revert "Use stable subscription channel"
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
Labels: lgtm, approved

#989 Release 2023 04 26.1.e65b562
  .github/pull_request_template.md
  .github/workflows/deploy-data-plane.yaml
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-production.yaml
  .github/workflows/deploy-stage.yaml
  Makefile
  cmd/fleet-manager/main.go
  dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
  deploy/helm/probe/deploy.sh
  deploy/helm/probe/templates/01-operator-04-deployment.yaml
  deploy/helm/probe/values.yaml
  dev/env/defaults/00-defaults.env
  dev/env/manifests/rhacs-operator/marketplace/03-subscription.yaml
  dev/env/manifests/rhacs-operator/quay/03-subscription.yaml
  dev/env/scripts/lib.sh
  docs/development/setup-osd-cluster-idp.md
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
  dp-terraform/helm/rhacs-terraform/charts/logging/README.md
  dp-terraform/helm/rhacs-terraform/charts/logging/templates/02-eventrouter-01-rbac.yaml
  dp-terraform/helm/rhacs-terraform/charts/logging/templates/02-eventrouter-02-configmap.yaml
  dp-terraform/helm/rhacs-terraform/charts/logging/templates/02-eventrouter-03-deployment.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/osd-cluster-idp-setup.sh
  fleetshard/main.go
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
  go.mod
  go.sum
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_versions.go
  internal/dinosaur/pkg/clusters/standalone_provider.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/wellknown/cloud_regions.go
  internal/dinosaur/pkg/wellknown/cloud_regions_test.go
  internal/dinosaur/pkg/wellknown/doc.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/accepted_centrals_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/ready_dinosaurs_mgr.go
  internal/dinosaur/providers.go
  openapi/fleet-manager-private.yaml
  pkg/client/fleetmanager/auth.go
  pkg/client/fleetmanager/auth_ocm.go
  pkg/environments/environment.go
  pkg/logger/logger.go
  pkg/providers/core.go
  probe/pkg/metrics/metrics.go
  probe/pkg/metrics/metrics_test.go
  probe/pkg/metrics/server_test.go
  probe/pkg/probe/probe.go
  probe/pkg/runtime/runtime.go
  tools/go.mod
  tools/go.sum
Labels: lgtm, approved

#985 update prod observability operator to v4.2.1
  dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm

#951 ROX-15941: Run multiple operators from FSS
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/test.sh
  fleetshard/README.md
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-deployment.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-manager-metrics-service_v1_service.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-service-account.yaml
  fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
  fleetshard/pkg/central/operator/upgrade.go
  fleetshard/pkg/central/operator/upgrade_test.go
  fleetshard/pkg/runtime/runtime.go
Labels: approved
