Repository stackrox/acs-fleet-manager, pull requests merged in 2023-09, with the labels that each got.

#1235 chore: fix probe log when response if empty
  probe/pkg/probe/probe.go
  probe/pkg/runtime/runtime.go
Labels: lgtm, approved

#1239 fix: typo in quoata
  docs/legacy/architecture/quota-service-implementation.md
  docs/legacy/images/quota-service.png
  internal/dinosaur/pkg/services/quota/default_quota_service_factory.go
  internal/dinosaur/pkg/services/quota_service_factory.go
  internal/dinosaur/pkg/services/quota_service_factory_moq.go
Labels: lgtm

#1197 ROX-18430: restore secrets from fleet-manager in fleetshard-sync
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/api_agent_clusters.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_metadata.go
  internal/dinosaur/pkg/handlers/data_plane_dinosaur.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/routes/route_loader.go
  openapi/fleet-manager-private.yaml
  pkg/client/fleetmanager/api_moq.go
  pkg/client/fleetmanager/client.go
Labels: lgtm, approved

#1231 ROX-19013: Add docker environment
  dev/env/defaults/05-docker.env
  dev/env/defaults/cluster-type-docker/env
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#1229 ROX-19494: Bump wait time and provide context for initialization.
  dev/env/scripts/up.sh
  e2e/e2e_auth_test.go
  e2e/e2e_test.go
  fleetshard/config/config.go
  fleetshard/main.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/cmd/admin/centrals/list.go
  internal/dinosaur/pkg/cmd/centrals/create.go
  internal/dinosaur/pkg/cmd/centrals/delete.go
  internal/dinosaur/pkg/cmd/centrals/get.go
  internal/dinosaur/pkg/cmd/centrals/list.go
  internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
  pkg/client/fleetmanager/auth.go
  pkg/client/fleetmanager/auth_ocm.go
  pkg/client/fleetmanager/auth_rhsso.go
  pkg/client/fleetmanager/auth_static_token.go
  probe/cmd/probe/main.go
  probe/internal/cli/cli.go
  probe/pkg/fleetmanager/client.go
  scripts/lib/log.sh
Labels: lgtm, approved

#1242 Revert "ROX-19494: Bump wait time and provide context for initialization."
  dev/env/scripts/up.sh
  e2e/e2e_auth_test.go
  e2e/e2e_test.go
  fleetshard/config/config.go
  fleetshard/main.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/cmd/admin/centrals/list.go
  internal/dinosaur/pkg/cmd/centrals/create.go
  internal/dinosaur/pkg/cmd/centrals/delete.go
  internal/dinosaur/pkg/cmd/centrals/get.go
  internal/dinosaur/pkg/cmd/centrals/list.go
  internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
  pkg/client/fleetmanager/auth.go
  pkg/client/fleetmanager/auth_ocm.go
  pkg/client/fleetmanager/auth_rhsso.go
  pkg/client/fleetmanager/auth_static_token.go
  probe/cmd/probe/main.go
  probe/internal/cli/cli.go
  probe/pkg/fleetmanager/client.go
  scripts/lib/log.sh
Labels: lgtm, approved

#1243 fix(probe): improve probe logging
  probe/pkg/probe/probe.go
  probe/pkg/runtime/runtime.go
Labels: lgtm

#1249 ROX-19228: ACS CS connection string updates for 4.2
  fleetshard/pkg/central/postgres/dbconnection.go
  fleetshard/pkg/central/postgres/dbconnection_test.go
  fleetshard/pkg/central/postgres/dbinit.go
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#1244 ROX-19494: Increase timeout and improve debugability of e2e test.
  dev/env/scripts/up.sh
  fleetshard/main.go
  scripts/lib/log.sh
Labels: lgtm, approved

#1246 Rename acsms -> acscs in proxy_test.go and dinosaurs_auth_config_mgr.go
  fleetshard/pkg/central/reconciler/proxy_test.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
Labels: lgtm, approved

#1255 Release 2023 09 12.1.f6d113e
  .secrets.baseline
  README.md
  dev/env/defaults/05-docker.env
  dev/env/defaults/cluster-type-docker/env
  dev/env/scripts/exec_fleetshard_sync.sh
  dev/env/scripts/lib.sh
  dev/env/scripts/up.sh
  docs/development/howto-e2e-test-rds.md
  docs/legacy/architecture/quota-service-implementation.md
  docs/legacy/images/quota-service.png
  fleetshard/main.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
  fleetshard/pkg/central/cloudprovider/dbclient.go
  fleetshard/pkg/central/postgres/dbconnection.go
  fleetshard/pkg/central/postgres/dbconnection_test.go
  fleetshard/pkg/central/postgres/dbinit.go
  fleetshard/pkg/central/reconciler/proxy_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
  go.mod
  go.sum
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/api_default.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/api_agent_clusters.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_metadata.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec.go
  internal/dinosaur/pkg/config/central.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/data_plane_dinosaur.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/dinosaurservice_moq.go
  internal/dinosaur/pkg/services/quota/default_quota_service_factory.go
  internal/dinosaur/pkg/services/quota_service_factory.go
  internal/dinosaur/pkg/services/quota_service_factory_moq.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
  openapi/fleet-manager-private-admin.yaml
  openapi/fleet-manager-private.yaml
  pkg/client/fleetmanager/api_moq.go
  pkg/client/fleetmanager/client.go
  probe/pkg/probe/probe.go
  probe/pkg/runtime/runtime.go
  scripts/lib/log.sh
  templates/service-template.yml
Labels: lgtm, approved

#1253 obscure data in fleetshard-sync status logs
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#1198 ROX-18427: read central DB ID override from optional ConfigMap
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#1254 ROX-16085: Support integration env in grafana dashboard.
  dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
  dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
Labels: lgtm, approved

#1241 ROX-19558: Mount gitops config to Fleet Manager
  templates/service-template.yml
Labels: lgtm, approved

#1236 ROX-11640: RHSSO dynamic clients rotation API
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/api_default.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/rhsso/augment.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/dinosaurservice_moq.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
  openapi/fleet-manager-private-admin.yaml
  pkg/errors/errors.go
Labels: approved

#1226 Add tools image for CI runs
  .github/workflows/ci.yaml
  Dockerfile.tools
  Makefile
  build_push_fleet_manager_tools.sh
Labels: approved, do-not-merge/work-in-progress

#1258 Remove unsued `image/build/local` Makefile target
  Makefile
Labels: approved

#1130 Add egress diagram to docs
  docs/architecture/images/egress_diagram.md
Labels: approved

#1267 Fix probe build env vars
  build_push_probe.sh
Labels: lgtm, approved

#1268 Fix probe build sourcing the script - round 3
  build_push_probe.sh
Labels: lgtm, approved

#1245 ROX-19588: Log HTTP error response
  internal/dinosaur/pkg/rhsso/augment.go
Labels: approved

#1269 ROX-19480: Add GitOps provider alert
  internal/dinosaur/pkg/gitops/provider.go
  internal/dinosaur/pkg/gitops/provider_test.go
  pkg/metrics/metrics.go
Labels: lgtm, approved

#1266 ROX=19699: Combine data for creating latency SLO chart
  dashboards/grafana-dashboard-acs-fleet-manager-slos.configmap.yaml
Labels: lgtm, approved

#1270 ROX-19480: Fix GitOps provider alert
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleet-manager/03-fleet-manager-service.yaml
  pkg/metrics/metrics.go
Labels: approved

#1214 Fix local dev env when using ACS 4.2 without OLM
  dev/env/manifests/monitoring/01-namespace.yaml
  dev/env/manifests/monitoring/02-monitoring.coreos.com_prometheusrules.yaml
  dev/env/manifests/monitoring/03-monitoring.coreos.com_servicemonitors.yaml
  dev/env/scripts/bootstrap.sh
Labels: lgtm, approved

#1273 ROX-19725: Push observability stage branch to stage env
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1261 ROX-19690: Push to stage environment from stage branch, not main
  .github/workflows/deploy-stage.yaml
Labels: lgtm, approved

#1275 Use Openshift golang-1.20 builder image
  .openshift-ci/e2e-runtime/Dockerfile
  Dockerfile
  probe/Dockerfile
Labels: lgtm, approved

#1256 Add kind cluster type
  Makefile
  dev/config/dataplane-cluster-configuration-kind.yaml
  dev/env/defaults/05-kind.env
  dev/env/defaults/cluster-type-kind/env
  dev/env/scripts/docker.sh
  dev/env/scripts/lib.sh
Labels: lgtm, approved

#1276 Refactor operator config to use field.Error
  fleetshard/pkg/central/operator/config.go
  fleetshard/pkg/central/operator/config_test.go
  fleetshard/pkg/central/operator/upgrade.go
Labels: lgtm, approved

#1277 fixed typo causing skip of DNS creation in restore
  internal/dinosaur/pkg/services/dinosaur.go
Labels: lgtm, approved

#1283 ROX-19718: Add flag for fleetmanager gitops
  Makefile
  dev/env/defaults/00-defaults.env
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleet-manager/04-gitops-config.yaml
  dev/env/scripts/lib.sh
  dev/env/scripts/update_gitops_config.sh
  e2e/e2e_test.go
  internal/dinosaur/pkg/gitops/module.go
  internal/dinosaur/pkg/gitops/provider.go
  pkg/providers/core.go
Labels: approved

#1272 Add request body to rotate-secrets endpoint
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/api_default.go
  internal/dinosaur/pkg/api/admin/private/model_central_rotate_secrets_request.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  openapi/fleet-manager-private-admin.yaml
Labels: lgtm, approved

#1286 Disable automounting for egress proxy
  fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
Labels: lgtm

#1290 ROX-19808: Remove GitOps admin handler
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
Labels: lgtm, approved

#1284 ROX-19692: Add a release preparation workflow.
  .github/workflows/start-release.yaml
Labels: lgtm, approved

#1278 ROX-19735 - add operator configs to gitops
  dev/env/manifests/fleet-manager/04-gitops-config.yaml
  fleetshard/pkg/central/operator/config.go
  fleetshard/pkg/central/operator/config_test.go
  fleetshard/pkg/central/operator/upgrade.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/gitops/config.go
  internal/dinosaur/pkg/gitops/config_test.go
  internal/dinosaur/pkg/handlers/data_plane_dinosaur.go
  internal/dinosaur/pkg/routes/route_loader.go
Labels: approved

#1291 ROX-19692: New workflow to auto-create production merge PRs.
  .github/workflows/create-prod-pr.yaml
Labels: lgtm, approved

#1292 ROX-19810: Bump controller-runtime and stackrox deps
  go.mod
  go.sum
Labels: lgtm, approved

#1289 Call /current_account before reserving quota
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/handlers/dinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/dinosaurservice_moq.go
  internal/dinosaur/pkg/services/quota.go
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
  internal/dinosaur/pkg/services/quota/quota_management_list_service.go
  internal/dinosaur/pkg/services/quota/quota_management_list_service_test.go
  internal/dinosaur/pkg/services/quotaservice_moq.go
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
Labels: lgtm, approved

#1259 Remove multi target build
  Dockerfile
  Dockerfile.local
  Makefile
  dev/env/defaults/00-defaults.env
  dev/env/scripts/docker.sh
  dev/env/scripts/lib.sh
  dev/env/scripts/up.sh
  probe/Dockerfile
Labels: lgtm, approved

#1298 fixed restore endpoint
  fleetshard/pkg/central/reconciler/reconciler.go
  internal/dinosaur/pkg/services/dinosaur.go
Labels: lgtm, approved

#1297 Log result of current_account call execution
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
Labels: lgtm, approved

#1307 Adding CODEOWNERS to semi-lock the Helm chart
  CODEOWNERS
Labels: lgtm, approved

#1306 Add a few messages about probe progress.
  probe/pkg/probe/probe.go
Labels: lgtm, approved

#1285 ROX-16664: add KeyGenerator interface and implementations
  fleetshard/pkg/cipher/aes256_cipher.go
  fleetshard/pkg/cipher/aes256_cipher_test.go
  fleetshard/pkg/cipher/key_generator.go
  fleetshard/pkg/cipher/kms_cipher.go
  fleetshard/pkg/cipher/kms_cipher_test.go
Labels: lgtm, approved

#1295 ROX-16664: create central encryption secret
  e2e/e2e_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/cipher/cipher.go
  fleetshard/pkg/runtime/runtime.go
Labels: approved
