Repository stackrox/acs-fleet-manager, pull requests merged in 2023-05, with the labels that each got.

#992 ROX-15980 probe resource requests and limits
  deploy/helm/probe/templates/01-operator-04-deployment.yaml
  deploy/helm/probe/values.yaml
Labels: lgtm, approved

#993 ROX-15980 observability resource requests and limits
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
  dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Labels: lgtm, approved

#990 ROX-15980: Set resources requests and limits for fleetshard-sync
  dp-terraform/helm/rhacs-terraform/README.md
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: approved

#995 ROX-16769 add resources for observability operator
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-05-subscription.yaml
  dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Labels: approved

#991 ROX-15980 set resource requests and limits to the egress-proxy
  e2e/e2e_test.go
  fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
  fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#1007 fix e2e admin tests by reducing required resources
  e2e/e2e_test.go
Labels: approved

#994 ROX-13692: create final snapshot for tenant db
  .github/workflows/rds.yaml
  Makefile
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
Labels: approved

#1009 Revert "ROX-13692: create final snapshot for tenant db (#994)"
  .github/workflows/rds.yaml
  Makefile
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
Labels: lgtm, approved

#1006 ROX-15954: Setup non-admin access to observability resources
  dp-terraform/osd-cluster-idp-setup.sh
Labels: approved

#996 ROX-16791: Increase route timeout to 10m to allow for longer operations
  fleetshard/pkg/k8s/route.go
Labels: lgtm

#1013 ROX-16894: Enable CloudWatch log exports for new RDS DBs
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
Labels: lgtm, approved

#723 ROX-16883: Increase resource limits
  internal/dinosaur/pkg/defaults/default_central_spec.go
  internal/dinosaur/pkg/defaults/default_scanner_spec.go
Labels: lgtm

#1005 Upgrade go version to 1.20
  .github/workflows/ci.yaml
  .github/workflows/deploy-data-plane.yaml
  .github/workflows/pre-commit.yaml
  .github/workflows/probe.yaml
  .github/workflows/rds.yaml
  .golangci.yml
  .openshift-ci/e2e-runtime/Dockerfile
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  README.md
  go.mod
  internal/dinosaur/pkg/services/data_migration.go
  probe/Dockerfile
  tools/go.mod
Labels: lgtm, approved

#954 ROX-16338: Refactor helm chart installation
  fleetshard/pkg/central/charts/charts.go
  fleetshard/pkg/central/charts/charts_test.go
  fleetshard/pkg/central/charts/testdata/test-chart/Chart.yaml
  fleetshard/pkg/central/charts/testdata/test-chart/templates/dummy.yaml
  fleetshard/pkg/central/charts/testdata/test-chart/values.yaml
  fleetshard/pkg/central/operator/upgrade.go
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: approved

#998 Add admin API client
  cmd/fleet-manager/main.go
  internal/dinosaur/pkg/cmd/admin/centrals/cmd.go
  internal/dinosaur/pkg/cmd/admin/centrals/list.go
  internal/dinosaur/pkg/cmd/admin/cmd.go
  internal/dinosaur/pkg/cmd/fleetmanagerclient/client.go
  pkg/client/fleetmanager/auth_ocm.go
  pkg/client/fleetmanager/auth_rhsso.go
  pkg/client/fleetmanager/auth_static_token.go
Labels: lgtm, approved

#1012 ROX-13692: fix final snapshot creation
  .github/workflows/rds.yaml
  Makefile
  dev/config/dataplane-cluster-configuration-crc.yaml
  docs/development/howto-e2e-test-rds.md
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
Labels: approved

#1018 ROX-13692: skip final snapshots for probe
  .secrets.baseline
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
  fleetshard/pkg/central/cloudprovider/dbclient.go
  fleetshard/pkg/central/cloudprovider/dbclient_moq.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#1020 ROX-16561: Do not export RDS/Postgres logs to CloudWatch for Probe instances
  .secrets.baseline
  fleetshard/pkg/central/cloudprovider/awsclient/rds.go
  fleetshard/pkg/central/cloudprovider/awsclient/rds_test.go
  fleetshard/pkg/central/cloudprovider/dbclient.go
  fleetshard/pkg/central/cloudprovider/dbclient_moq.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#1029 add FM_URL env variable for fmcurl script
  scripts/fmcurl
Labels: lgtm, approved

#1036 ROX-17002: Bump stackrox dependency
  go.mod
  go.sum
Labels: lgtm, approved

#1019 add AWS pr checks
  .github/pull_request_template.md
Labels: lgtm, approved

#1064 Fix central count log message deduplication
  pkg/logger/logger.go
  pkg/logger/logger_test.go
Labels: lgtm, approved
