Repository stackrox/acs-fleet-manager, pull requests merged in 2024-02, with the labels that each got.

#1608 ROX-21779 Set new FM_ENDPOINT for stage and production
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1633 Fix missing PackageImage field in clusters_mgmt
  go.mod
  go.sum
  internal/dinosaur/pkg/services/addon.go
  internal/dinosaur/pkg/services/addon_test.go
  pkg/client/ocm/client.go
  pkg/client/ocm/impl/client_impl.go
  pkg/client/ocm/mocks/client_moq.go
Labels: lgtm, approved

#1632 Remove dev and integration from dp-terraform
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-integration.yaml
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/ocm/install_addon.sh
Labels: lgtm, approved

#1636 Add fleetshardSync.addonName helm value
  dp-terraform/helm/Dockerfile
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  dp-terraform/helm/watches.yaml
Labels: lgtm, approved

#1619 ROX-21946: FS set central-tls OwnerReference if not already set
  .secrets.baseline
  e2e/e2e_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/k8s/route.go
  fleetshard/pkg/k8s/route_test.go
  fleetshard/pkg/k8s/secret.go
Labels: lgtm, approved

#1629 ROX-20872: fix fleetshard reconciler race condition
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: approved

#1638 Keep central hash when central is ready
  fleetshard/pkg/central/reconciler/reconciler.go
Labels: lgtm, approved

#1639 fix: log message argument
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
Labels: lgtm, approved

#1634 ROX-22235 add AWS SES cloudwatch-exporter job
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
Labels: lgtm, approved

#1640 feat: expose `expired-at` via Telemetry
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/telemetry.go
Labels: lgtm

#1645 Delete terraform_cluster.sh
  .github/workflows/deploy-data-plane.yaml
  .github/workflows/deploy-dev.yaml
  .github/workflows/deploy-integration.yaml
  .github/workflows/deploy-production.yaml
  .github/workflows/deploy-stage.yaml
  dp-terraform/helm/.dockerignore
  dp-terraform/helm/rhacs-terraform/README.md
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
  dp-terraform/helm/rhacs-terraform/test.sh
Labels: lgtm, approved

#1651 ROX-22237: Bump ocm-sdk-go and switch it back to upstream
  go.mod
  go.sum
Labels: lgtm, approved

#1662 Add the addon step to the PR checklist
  .github/pull_request_template.md
Labels: lgtm, approved

#1666 ROX-16615: Add probe image build on app-interface
  build_push_app_interface.sh
Labels: lgtm, approved

#1669 Bump stackrox deps 190983eddb0a
  go.mod
  go.sum
  internal/dinosaur/pkg/gitops/default_central_test.go
Labels: lgtm, approved

#1674 fix(scannerv4): adjust proxy settings
  fleetshard/pkg/central/reconciler/proxy.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#1663 ROX-22358: reset grace period on restore
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/dinosaur_test.go
Labels: lgtm, approved

#1677 ROX-22557: Count `expired-at` non-null changes
  internal/dinosaur/pkg/workers/dinosaurmgrs/expiration_date_mgr.go
  pkg/metrics/metrics.go
Labels: lgtm
