Repository stackrox/acs-fleet-manager, pull requests merged in 2024-08, with the labels that each got.

#1950 introduce global.image.tag for rhacs-terraform helm chart
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: approved, ok-to-test

#1971 chore(terraform): bump cloudwatch exporter
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/values.yaml
Labels: lgtm, approved

#1970 Switch ACS operator in dev gitops config to fast stream
  dev/config/gitops-config.yaml
Labels: lgtm, approved

#1972 fix(terraform): cloudwatch exporter config
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
Labels: lgtm, approved

#1979 ROX-25605: Bump helm operator image base image
  Makefile
  dp-terraform/helm/Dockerfile
Labels: approved

#1981 ROX-24936: add abstraction for email.Sender to allow multiple impl
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  emailsender/cmd/app/main.go
  emailsender/config/config.go
  emailsender/pkg/email/sender.go
  emailsender/pkg/email/sender_test.go
  emailsender/pkg/email/ses.go
Labels: lgtm, approved

#1989 ROX-23367: Central Name Validation
  internal/dinosaur/pkg/handlers/validation.go
Labels: lgtm, approved

#1980 Improve dev deployments on infra clusters
  .github/workflows/ci.yaml
  .openshift-ci/image-push/entrypoint.sh
  Makefile
  README.md
  dev/env/defaults/00-defaults.env
  dev/env/defaults/02-infra.env
  dev/env/defaults/06-gke.env
  dev/env/defaults/cluster-type-gke/env
  dev/env/defaults/cluster-type-infra-openshift/env
  dev/env/manifests/fleetshard-operator/28-deployment.yaml
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/docker.sh
  dev/env/scripts/lib.sh
  docs/development/running-fleet-manager.md
Labels: approved

#1991 ROX-25847: add argocd types
  fleetshard/pkg/k8s/client.go
  go.mod
  go.sum
Labels: lgtm, approved

#1946 ROX-21530: Certificate Monitoring
  fleetshard/main.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/fleetshardmetrics/metrics.go
  fleetshard/pkg/k8s/client.go
  internal/certmonitor/certmonitor.go
  internal/certmonitor/certmonitor_test.go
Labels: lgtm, approved

#1987 ROX-24936: emailsender central compatibility test
  .github/workflows/emailsender-central-compatibility.yaml
  .gitignore
  Makefile
  dev/env/scripts/lib.sh
  emailsender/compatibility/emailsender_central_test.go
  emailsender/compatibility/post-acscsemail-integration.json
  scripts/ci/central_compatibility/central-values.yaml
  scripts/ci/central_compatibility/emailsender-db.yaml
  scripts/ci/central_compatibility/emailsender-values.yaml
  scripts/ci/central_compatibility/entrypoint.sh
  scripts/ci/central_compatibility/run_compatibility_test.sh
Labels: lgtm, approved

#1998 Fix certmonitor labelselector
  fleetshard/main.go
  internal/certmonitor/certmonitor.go
  internal/certmonitor/certmonitor_test.go
Labels: lgtm, approved

#1999 fix: add To header to emailsender emails
  emailsender/pkg/email/sender.go
  emailsender/pkg/email/sender_test.go
Labels: lgtm, approved
