Repository stackrox/acs-fleet-manager, pull requests merged in 2024-01, with the labels that each got.

#1547 ROX-21558: Cache docker image build
  Dockerfile
  Dockerfile.local
  Makefile
  dev/env/scripts/docker.sh
Labels: lgtm, approved

#1520 ROX-20479: service registration
  .github/workflows/ci.yaml
  .openshift-ci/tests/e2e-test.sh
  .secrets.baseline
  cmd/fleet-manager/main_test.go
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleet-manager/03-fleet-manager-service-active.yaml
  internal/dinosaur/test/helper.go
  pkg/providers/core.go
  pkg/serviceregistration/leader.go
  pkg/serviceregistration/leader_test.go
  pkg/serviceregistration/service.go
  pkg/workers/leader_election_mgr.go
  pkg/workers/leader_election_mgr_test.go
  templates/route-template.yml
  templates/service-template.yml
Labels: lgtm, approved

#1556 ROX-20479: fix pod permissions
  .secrets.baseline
  templates/service-template.yml
Labels: lgtm, approved

#1558 chore: reduce resync period
  dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Labels: lgtm, approved, 99papercuts

#1557 ROX-20479: fix leader retry
  pkg/serviceregistration/leader.go
Labels: approved

#1555 ROX-21596: add PVC for alertmanager
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
  dp-terraform/helm/rhacs-terraform/charts/observability/values.yaml
Labels: lgtm, approved, 99papercuts

#1561 Remove kubeconfig from fleet-manager
  .secrets.baseline
  Makefile
  config/dataplane-cluster-configuration.yaml
  dev/config/dataplane-cluster-configuration-minikube.yaml
  dev/config/dataplane-cluster-configuration-rancherdesktop.yaml
  dev/env/manifests/fleet-manager/01-fleet-manager-secrets.yaml
  dev/env/scripts/lib.sh
  docs/development/running-fleet-manager.md
  docs/legacy/data-plane-osd-cluster-options.md
  docs/legacy/feature-flags.md
  internal/dinosaur/pkg/clusters/standalone_provider.go
  internal/dinosaur/pkg/config/dataplane_cluster_config.go
  internal/dinosaur/test/helper.go
  templates/secrets-template.yml
  templates/service-template.yml
Labels: lgtm, approved

#1522 ROX-21070: Implement the addon mgmt in fleet manager
  internal/dinosaur/pkg/services/addon.go
  internal/dinosaur/pkg/services/addon_test.go
  internal/dinosaur/pkg/services/data_plane_cluster.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
  internal/dinosaur/pkg/workers/clusters_mgr_test.go
  internal/dinosaur/providers.go
  pkg/api/cluster_types.go
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
Labels: approved

#1540 ROX-21679: add rotate secret backup feature to admin API
  .secrets.baseline
  e2e/e2e_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/api_default.go
  internal/dinosaur/pkg/api/admin/private/model_central_rotate_secrets_request.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/dinosaurservice_moq.go
  openapi/fleet-manager-private-admin.yaml
  pkg/client/fleetmanager/api_moq.go
  pkg/client/fleetmanager/client.go
Labels: lgtm, approved

#1563 ROX-20479: fix fleet-manager service label
  templates/service-template.yml
Labels: lgtm, approved

#1571 ROX-20479: fix fleet-manager-active cert label
  templates/service-template.yml
Labels: approved

#1572 ROX-20479: fix fleet-manager-active cert
  .secrets.baseline
  templates/service-template.yml
Labels: approved

#1573 ROX-20479: revert fleet-manager-active cert
  templates/service-template.yml
Labels: approved

#1550 ROX-18694: Bump envoy to 1.28.0 version
  templates/service-template.yml
Labels: approved

#1574 ROX-20479: fleet-manager-active certs
  templates/service-template.yml
Labels: lgtm, approved

#1575 ROX-20479: fleet-manager-active certs
  templates/service-template.yml
Labels: approved

#1577 ROX-20479: fleet-manager-active certs
  templates/service-template.yml
Labels: approved

#1579 ROX-20479: fleet-manager-active certs
  templates/service-template.yml
Labels: lgtm, approved

#1580 Revert "ROX-20479: fleet-manager-active certs (#1579)"
  templates/service-template.yml
Labels: approved

#1581 ROX-18694: Add tls to backend cluster
  templates/service-template.yml
Labels: lgtm, approved

#1582 ROX-20479: re-add active tls cert
  templates/service-template.yml
Labels: lgtm, approved

#1583 ROX-20479: re-add active tls cert
  templates/service-template.yml
Labels: approved

#1585 ROX-20479: add duplicate filter chain for active fleet-manager
  templates/service-template.yml
Labels: approved

#1588 Temporarily disable integration tests on CI
  .github/workflows/ci.yaml
Labels: lgtm, approved

#1589 ROX-20479: adding all possible fleet-manager-active hostnames to envoy config
  templates/service-template.yml
Labels: approved

#1587 ROX-20479: adding envoy log level parameter
  .secrets.baseline
  templates/service-template.yml
Labels: lgtm, approved

#1592 Revert "ROX-20479: only use active-tls cert (#1591)"
  templates/service-template.yml
Labels: approved

#1594 Fix integration tests and enable them back on CI
  .github/pull_request_template.md
  .github/workflows/ci.yaml
  Makefile
Labels: lgtm, approved

#1603 ROX-21779 Try app-protocol annotation
  templates/service-template.yml
Labels: approved

#1602 ROX-21779 Add envoy active listener
  templates/service-template.yml
Labels: lgtm, approved

#1605 ROX-21779 Set new FM_ENDPOINT for integration
  dp-terraform/helm/rhacs-terraform/terraform_cluster.sh
Labels: lgtm, approved

#1595 Fixed race condition in integration tests
  .github/workflows/ci.yaml
  .openshift-ci/tests/e2e-test.sh
  .secrets.baseline
  dev/env/scripts/lib.sh
  internal/dinosaur/pkg/environments/development.go
  internal/dinosaur/pkg/environments/integration.go
  pkg/db/dinosaur.go
  pkg/server/server_config.go
  pkg/serviceregistration/leader.go
  pkg/serviceregistration/service.go
  templates/service-template.yml
  test/helper.go
Labels: approved

#1601 Native arm64 docker build with buildkit
  .github/workflows/ci.yaml
  .openshift-ci/e2e-runtime/Dockerfile
  .openshift-ci/e2e-runtime/e2e_dockerized.sh
  Dockerfile
  Dockerfile.tools
  Makefile
  dev/env/scripts/docker.sh
  probe/Dockerfile
Labels: lgtm, approved

#1609 ROX-21779 Fix api-envoy-active port name too long error
  templates/service-template.yml
Labels: lgtm, approved

#1607 ROX-21695: Increase collector memory usage for CO-RE BPF collection method
  dp-terraform/helm/rhacs-terraform/charts/secured-cluster/values.yaml
Labels: lgtm, approved

#1596 ROX-21070: Set fleetshard sync image from Fleet Manager
  .secrets.baseline
  Makefile
  dev/env/defaults/00-defaults.env
  dev/env/manifests/fleet-manager/01-fleet-manager-secrets.yaml
  dev/env/scripts/lib.sh
  internal/dinosaur/pkg/environments/development.go
  internal/dinosaur/pkg/environments/integration.go
  internal/dinosaur/pkg/gitops/provider.go
  internal/dinosaur/pkg/services/addon.go
  internal/dinosaur/pkg/services/addon_test.go
  pkg/client/ocm/addon_config.go
  pkg/client/ocm/client.go
  pkg/client/ocm/client_moq.go
  pkg/client/ocm/config.go
  pkg/providers/core.go
  templates/secrets-template.yml
  templates/service-template.yml
Labels: approved

#1616 Allow for both "sub" claim formats to be used in login
  fleetshard/pkg/central/reconciler/reconciler.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_auth.go
  internal/dinosaur/pkg/handlers/validation.go
  internal/dinosaur/pkg/migrations/20240122180000_add_alternate_user_id.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  openapi/fleet-manager-private.yaml
  pkg/auth/acs_claims.go
  pkg/auth/context_config.go
Labels: lgtm, approved

#1617 fix: update for secret backup for tenants
  fleetshard/pkg/central/reconciler/reconciler.go
  internal/dinosaur/pkg/services/data_plane_dinosaur.go
Labels: approved

#1623 chore: enable unused and ginkgo linters
  .golangci.yml
  internal/dinosaur/pkg/services/cluster_placement_strategy_test.go
  internal/dinosaur/pkg/services/data_plane_cluster.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/util.go
  internal/dinosaur/pkg/services/util_test.go
Labels: lgtm
