Repository stackrox/acs-fleet-manager, pull requests merged in 2024-06, with the labels that each got.

#1847 ROX-23254: Add SendRawEmail method
  emailsender/pkg/email/ses.go
  emailsender/pkg/email/ses_test.go
Labels: lgtm, approved

#1802 ROX-23709: Load token from file in fleetshard-sync
  .secrets.baseline
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  dp-terraform/test/helm_template_test.go
  go.mod
  go.sum
  pkg/client/fleetmanager/impl/auth.go
  pkg/client/fleetmanager/impl/auth_service_account_token.go
  pkg/client/fleetmanager/impl/auth_service_account_token_test.go
  pkg/client/fleetmanager/impl/auth_test.go
  pkg/client/fleetmanager/impl/testdata/token
Labels: approved

#1850 ROX-23252: Fix default image value for email sender service
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1855 ROX-23708: Add quay RO user to operator SA
  fleetshard/pkg/central/charts/data/rhacs-operator/templates/rhacs-operator-service-account.yaml
Labels: lgtm, approved

#1859 ROX-23252: Automatically update email sender image tag
  Makefile
  dp-terraform/helm/Dockerfile
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
Labels: lgtm, approved

#1862 fix: emailsender cmd
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
Labels: lgtm, approved

#1863 Fix fleetmanager caching bug
  internal/dinosaur/pkg/presenters/managedcentral.go
Labels: lgtm, approved

#1864 Remove CODEOWNERS
  CODEOWNERS
Labels: lgtm, approved

#1866 ROX-24158: remove unnecessary field from tenant default network policy
  fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-default.yaml
Labels: lgtm, approved

#1860 ROX-23255: emailsender read auth cfg from kubernetes
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  emailsender/config/config.go
  emailsender/config/config_test.go
  emailsender/pkg/api/routes.go
  pkg/shared/tls.go
  pkg/shared/tls_test.go
Labels: approved

#1826 ROX-23255: add auth implementation for emailsender API
  config/emailsender-authz.yaml
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  emailsender/cmd/app/main.go
  emailsender/config/config.go
  emailsender/config/config_test.go
  emailsender/pkg/api/emailhandler.go
  emailsender/pkg/api/emailhandler_test.go
  emailsender/pkg/api/middleware.go
  emailsender/pkg/api/middleware_test.go
  emailsender/pkg/api/routes.go
  emailsender/pkg/api/routes_test.go
  pkg/auth/acs_claims.go
  pkg/auth/context_config.go
  pkg/auth/fleetshard_authz_middleware.go
  pkg/auth/fleetshard_authz_middleware_test.go
  pkg/errors/errors.go
  pkg/shared/tls.go
  pkg/shared/tls_test.go
Labels: approved

#1868 ROX-22549: Add an addon metric to track version mismatch
  internal/dinosaur/pkg/services/addon.go
  pkg/metrics/metrics.go
Labels: lgtm, approved

#1869 ROX-23249: multiple emailsender issues discovered by debugging
  dp-terraform/helm/rhacs-terraform/values.yaml
  emailsender/cmd/app/main.go
  emailsender/config/config.go
  emailsender/pkg/api/emailhandler.go
  emailsender/pkg/email/sender.go
Labels: lgtm, approved

#1870 ROX-20474: Add TENANT_IMAGE_PULL_SECRET to the dp-terraform helm chart
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  dp-terraform/test/helm_template_test.go
  fleetshard/config/config.go
Labels: lgtm, approved

#1872 ROX-22549: Change cluster_id label to cluster_name for the addon status metric
  internal/dinosaur/pkg/gitops/config.go
  internal/dinosaur/pkg/gitops/provider_test.go
  internal/dinosaur/pkg/services/addon.go
  internal/dinosaur/pkg/services/addon_test.go
  internal/dinosaur/pkg/workers/clusters_mgr.go
  pkg/metrics/metrics.go
Labels: lgtm, approved

#1873 ROX-21884: remove commented out tenant name change test
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
Labels: lgtm, approved

#1861 ROX-23253: add emailsender TLS service to helm template
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1880 ROX-22549: Remove excessive labels for the addon metric
  internal/dinosaur/pkg/services/addon.go
  pkg/metrics/metrics.go
Labels: lgtm, approved

#1881 ROX-23749: Allow Scanner V4 observability ingress on port 9091
  fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-scanner-v4.yaml
Labels: lgtm, approved

#1886 ROX-23749: allow indexer and scanner egress to kube API
  fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-scanner-v4.yaml
Labels: lgtm, approved

#1884 ROX-22549: Add the addon metric to the grafana dashboard
  dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
Labels: lgtm, approved

#1867 ROX-23260: Add Rate Limiter Service
  emailsender/cmd/app/main.go
  emailsender/config/config.go
  emailsender/pkg/db/connect.go
  emailsender/pkg/db/models.go
  emailsender/pkg/email/ratelimiter.go
  emailsender/pkg/email/ratelimiter_test.go
  emailsender/pkg/email/ses.go
Labels: approved

#1885 ROX-24660: install Compliance Operator on integration
  dp-terraform/helm/rhacs-terraform/Chart.lock
  dp-terraform/helm/rhacs-terraform/Chart.yaml
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/.helmignore
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/Chart.yaml
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/README.md
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/templates/01-namespace.yaml
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/templates/02-subscription.yaml
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/templates/03-operator-group.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: approved

#1889 ROX-23709: Fix the volume mount error
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
Labels: lgtm, approved

#1887 ROX-23260: Add Rate Limiter to Email Sender
  emailsender/cmd/app/main.go
  emailsender/pkg/api/emailhandler.go
  emailsender/pkg/api/emailhandler_test.go
  emailsender/pkg/email/sender.go
  emailsender/pkg/email/sender_test.go
Labels: lgtm, approved

#1891 ROX-23709: Fix token expiration
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
Labels: lgtm, approved

#1897 ROX-24792: remove compliance operator
  dp-terraform/helm/rhacs-terraform/Chart.lock
  dp-terraform/helm/rhacs-terraform/Chart.yaml
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/.helmignore
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/Chart.yaml
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/README.md
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/templates/01-namespace.yaml
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/templates/02-subscription.yaml
  dp-terraform/helm/rhacs-terraform/charts/compliance-operator/templates/03-operator-group.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1882 ROX-23260: add external secret for emailsender db config
  dp-terraform/helm/rhacs-terraform/templates/emailsender-secret.yaml
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
Labels: lgtm, approved

#1835 ROX-23967: Tenant network policies tests
  .openshift-ci/e2e-runtime/Dockerfile
  .openshift-ci/tests/e2e.sh
  .openshift-ci/tests/netpol-test.sh
  test/network-policy/fake-client/Chart.yaml
  test/network-policy/fake-client/templates/deployment.yaml
  test/network-policy/fake-client/values.yaml
  test/network-policy/fake-service/Chart.yaml
  test/network-policy/fake-service/templates/configmap.yaml
  test/network-policy/fake-service/templates/deployment.yaml
  test/network-policy/fake-service/templates/service.yaml
  test/network-policy/fake-service/values.yaml
Labels: lgtm, approved

#1899 ROX-23259: emailsender aws sts
  dp-terraform/helm/rhacs-terraform/templates/emailsender-secret.yaml
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
Labels: lgtm, approved

#1883 ROX-23258: add emailsender to egress NP for central
  fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-central.yaml
Labels: lgtm, approved

#1900 ROX-23260: Use fleetshardsync clusterName value
  dp-terraform/helm/rhacs-terraform/templates/emailsender-secret.yaml
Labels: lgtm, approved

#1901 ROX-23260: Use fleetshardsync cluster values
  dp-terraform/helm/rhacs-terraform/templates/emailsender.yaml
Labels: lgtm, approved

#1768 ROX 23555: Remove egress-proxy
  .secrets.baseline
  dev/config/gitops-config.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  e2e/e2e_canary_upgrade_test.go
  e2e/e2e_test.go
  fleetshard/config/config.go
  fleetshard/pkg/central/charts/data/tenant-resources/config/squid.conf
  fleetshard/pkg/central/charts/data/tenant-resources/templates/egress-proxy.yaml
  fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
  fleetshard/pkg/central/reconciler/proxy.go
  fleetshard/pkg/central/reconciler/proxy_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/central/reconciler/testdata/tenant-resources/templates/dummy.yaml
  fleetshard/pkg/central/reconciler/zzz_managed_resources.go
  fleetshard/pkg/runtime/runtime.go
  go.mod
  internal/dinosaur/pkg/gitops/service_test.go
Labels: lgtm, approved

#1904 ROX-23260: Setup rate limiter
  emailsender/cmd/app/main.go
  emailsender/pkg/email/ratelimiter.go
Labels: lgtm, approved

#1905 ROX-24844: Add a script to easily import an init-bundle to Secrets Manager
  scripts/import_init_bundle.sh
Labels: lgtm, approved

#1911 ROX-24844: Init bundle script fixes
  scripts/import_init_bundle.sh
Labels: lgtm, approved, ok-to-test

#1912 ROX-23260: Use orgID for tenantID
  emailsender/pkg/api/emailhandler.go
  pkg/auth/acs_claims.go
  pkg/auth/acs_claims_test.go
Labels: lgtm, approved

#1898 ROX-24867: Add Probe CPU Limits
  templates/probe-template.yml
Labels: lgtm, approved

#1916 ROX-24867: Fix string value of cpu limits
  templates/probe-template.yml
Labels: lgtm, approved

#1915 Use emailsender clusterName in secret
  dp-terraform/helm/rhacs-terraform/templates/emailsender-secret.yaml
Labels: lgtm, approved

#1890 ROX-11558: Run fleetshard-operator on dev/CI environments
  .openshift-ci/tests/e2e.sh
  Dockerfile
  Makefile
  dev/env/defaults/00-defaults.env
  dev/env/manifests/emailsender/01-emailsender-deployment.yaml
  dev/env/manifests/fleetshard-operator/01-fleetshard-crd.yaml
  dev/env/manifests/fleetshard-operator/07-serviceaccount.yaml
  dev/env/manifests/fleetshard-operator/15-clusterrole.yaml
  dev/env/manifests/fleetshard-operator/17-clusterrolebinding.yaml
  dev/env/manifests/fleetshard-operator/19-role.yaml
  dev/env/manifests/fleetshard-operator/21-rolebinding.yaml
  dev/env/manifests/fleetshard-operator/28-deployment.yaml
  dev/env/manifests/fleetshard-operator/51-fleetshard-cr.yaml
  dev/env/manifests/fleetshard-sync/01-fleetshard-sync-secrets.yaml
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-rbac.yaml
  dev/env/manifests/fleetshard-sync/03-fleetshard-sync-deployment.yaml
  dev/env/manifests/vertical-pod-autoscaler-olm/01-namespace.yaml
  dev/env/manifests/vertical-pod-autoscaler-olm/02-subscription.yaml
  dev/env/manifests/vertical-pod-autoscaler-olm/03-operator-group.yaml
  dev/env/manifests/vertical-pod-autoscaler-olm/README.md
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/create-imagepullsecrets
  dev/env/scripts/docker.sh
  dev/env/scripts/down.sh
  dev/env/scripts/exec_emailsender.sh
  dev/env/scripts/lib.sh
  dev/env/scripts/reset
  dev/env/scripts/up.sh
  dp-terraform/helm/Dockerfile
  dp-terraform/helm/rhacs-terraform/Chart.lock
  dp-terraform/helm/rhacs-terraform/Chart.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/templates/scc.yaml
  dp-terraform/helm/rhacs-terraform/templates/secret-store.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  dp-terraform/test/helm_template_test.go
  e2e/e2e_test.go
Labels: lgtm, approved

#1919 ROX-22549: Refine the addon metrics reporting
  dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
  internal/dinosaur/pkg/services/addon.go
  internal/dinosaur/pkg/services/addon_test.go
  pkg/metrics/metrics.go
Labels: approved

#1921 Use the github role instead of the technical user in AWS integration tests
  .github/workflows/aws-integration.yaml
  dev/env/scripts/exec_fleetshard_sync.sh
Labels: approved
