Repository stackrox/acs-fleet-manager, pull requests merged in 2024-04, with the labels that each got.

#1735 chore: dependabot upgrade gha
  .github/dependabot.yaml
Labels: lgtm

#1747 ROX-23370: add requests and limits to FM initContainer
  templates/service-template.yml
Labels: lgtm, approved

#1749 ROX-16615: Remove empty cpu limits from the probe Deployment
  templates/probe-template.yml
Labels: lgtm, approved

#1732 fix: consider zero-cost resources allowed
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
Labels: lgtm

#1757 ROX-16615: run probe cleanup after all specs have been completed
  probe/pkg/runtime/runtime.go
Labels: lgtm, approved

#1760 ROX-23607: Rotate fleet manager static tokens
  .secrets.baseline
  config/jwks-file-static.json
  config/static-token-admin-payload.json
  docs/development/test-locally-static-token.md
  templates/service-template.yml
Labels: lgtm, approved

#1762 ROX-16615: Delete probe helm chart
  deploy/helm/probe/.helmignore
  deploy/helm/probe/Chart.yaml
  deploy/helm/probe/README.md
  deploy/helm/probe/deploy.sh
  deploy/helm/probe/templates/01-secret-ocm-token.yaml
  deploy/helm/probe/templates/01-secret-rhsso-client-secret.yaml
  deploy/helm/probe/templates/02-deployment.yaml
  deploy/helm/probe/values.yaml
  dp-terraform/cd-robot-account-setup.sh
  scripts/lib/helm.sh
Labels: lgtm, approved

#1714 ROX-23219: Specify additional tenant's auth via gitops
  .secrets.baseline
  fleetshard/pkg/central/reconciler/reconciler.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_additional_auth_provider.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_additional_auth_provider_groups.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_additional_auth_provider_oidc.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_spec_additional_auth_provider_required_attributes.go
  internal/dinosaur/pkg/gitops/config.go
  internal/dinosaur/pkg/gitops/config_test.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  openapi/fleet-manager-private.yaml
Labels: lgtm, approved

#1764 ROX-23557: Add annotation for ACL Logging to tenant namespaces
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#1763 ROX-23559: Export Violation Denial Metrics
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
Labels: lgtm, approved

#1754 ROX-23251: Add base for email sender service
  emailsender/.gitignore
  emailsender/README.md
  emailsender/cmd/app/main.go
  emailsender/config/config.go
  emailsender/config/config_test.go
Labels: lgtm, approved

#1755 ROX-23251: Add metrics for email sender service
  emailsender/README.md
  emailsender/cmd/app/main.go
  emailsender/config/config.go
  emailsender/config/config_test.go
  emailsender/pkg/metrics/metrics.go
  emailsender/pkg/metrics/metrics_test.go
  emailsender/pkg/metrics/server.go
  emailsender/pkg/metrics/server_test.go
Labels: lgtm, approved

#1756 ROX-23251: Add local deployment for email sender service
  Makefile
  emailsender/Dockerfile
  emailsender/config/config_test.go
Labels: approved

#1775 fix: Remove eu-west-1 regions for cloudwatch exporter
  dp-terraform/helm/rhacs-terraform/charts/cloudwatch/templates/01-operator-03-config-map.yaml
Labels: lgtm, approved

#1767 ROX-23550: Add NetworkPolicy to Tenant Helm chart
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  fleetshard/config/config.go
  fleetshard/pkg/central/charts/data/tenant-resources/config/local-network-cidr-ranges-ipv6.yaml.tpl
  fleetshard/pkg/central/charts/data/tenant-resources/config/local-network-cidr-ranges.yaml.tpl
  fleetshard/pkg/central/charts/data/tenant-resources/templates/_helpers.tpl
  fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-central.yaml
  fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-default.yaml
  fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-scanner-v4.yaml
  fleetshard/pkg/central/charts/data/tenant-resources/templates/network-policy-scanner.yaml
  fleetshard/pkg/central/charts/data/tenant-resources/values.yaml
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/runtime/runtime.go
Labels: lgtm, approved

#1779 ROX 23550: Fix deployment, quote parameter
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
Labels: lgtm, approved

#1776 feat: enable scanner-v4 monitoring
  internal/dinosaur/pkg/gitops/default_central.yaml
  internal/dinosaur/pkg/gitops/default_central_test.go
Labels: lgtm, approved
