Repository stackrox/acs-fleet-manager, pull requests merged in 2024-07, with the labels that each got.

#1920 ROX-24936: add AWS integration test for emailsender
  Makefile
  emailsender/pkg/email/ses_integration_test.go
Labels: lgtm, approved

#1926 ROX-24458: Move app interface CI to podman
  Makefile
  build_push_app_interface.sh
  scripts/build_setup.sh
Labels: lgtm, approved

#1930 ROX-25022: emailsender dev docs
  Makefile
  emailsender/README.md
  emailsender/pkg/db/models.go
Labels: lgtm, approved

#1931 ROX-24458: Add podman support for dockerfile
  Dockerfile
Labels: lgtm, approved

#1923 ROX-23261: Add email sender metrics
  emailsender/pkg/email/sender.go
  emailsender/pkg/metrics/metrics.go
  emailsender/pkg/metrics/metrics_test.go
Labels: lgtm, approved

#1932 ROX-24458: probe build fix
  build_push_app_interface.sh
Labels: lgtm, approved

#1918 ROX-23967: Add more tenant network policy tests
  .openshift-ci/tests/netpol-test.sh
Labels: lgtm, approved

#1924 fix: add a cleanup job for email events
  emailsender/cmd/app/main.go
  emailsender/config/config.go
  emailsender/pkg/db/connect.go
  emailsender/pkg/db/mock.go
  emailsender/pkg/email/ratelimiter_test.go
  emailsender/pkg/workers/cleanup.go
  emailsender/pkg/workers/cleanup_test.go
Labels: lgtm, approved

#1903 Drop redundant resource values for rbac proxy
  fleetshard/pkg/central/charts/data/rhacs-operator/values.yaml
Labels: lgtm, approved

#1935 ROX-21290: fix rbac
  fleetshard/pkg/central/charts/data/rhacs-vertical-pod-autoscaler/templates/recommender-rbac.yaml
Labels: lgtm, approved

#1933 ROX-22354: autorotate DP secrets if data has changed
  .secrets.baseline
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/dbapi/data_plane_central_status.go
  internal/dinosaur/pkg/api/private/api/openapi.yaml
  internal/dinosaur/pkg/api/private/model_data_plane_central_status.go
  internal/dinosaur/pkg/api/private/model_managed_central_all_of_metadata.go
  internal/dinosaur/pkg/migrations/20240122180000_add_alternate_user_id copy.go
  internal/dinosaur/pkg/migrations/20240703120000_add_secret_data_sha256_sum_to_central_request.go
  internal/dinosaur/pkg/migrations/migrations.go
  internal/dinosaur/pkg/presenters/data_plane_dinosaur_status.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/data_plane_dinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  openapi/fleet-manager-private.yaml
Labels: lgtm, approved, 99papercuts

#1939 Restore go dependency caching with layers
  Dockerfile
Labels: lgtm, approved

#1940 ROX-23263: move from OSCI cluster pool to infra clusters for e2e
  .openshift-ci/begin.sh
  .openshift-ci/end.sh
  pkg/client/iam/config.go
  scripts/ci/lib.sh
Labels: lgtm, approved

#1942 ROX-25276: emailsender auth on rosa
  emailsender/config/config.go
  emailsender/config/config_test.go
Labels: lgtm, approved

#1906 ROX-24895: Migrate from fluentd logging to vector logging
  dp-terraform/helm/rhacs-terraform/charts/logging/templates/01-logging-03-cluster-logging.yaml
Labels: lgtm, approved

#1943 fix: revert accidental filename change
  internal/dinosaur/pkg/migrations/20240122180000_add_alternate_user_id.go
Labels: lgtm, approved

#1949 ROX-23709: Disable RHSSO issuer for fleetshard authZ
  .secrets.baseline
  README.md
  config/fleetshard-authz-development.yaml
  config/fleetshard-authz-prod.yaml
  dev/config/gitops-config.yaml
  dev/env/scripts/lib.sh
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync-secret.yaml
  dp-terraform/helm/rhacs-terraform/templates/fleetshard-sync.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
  e2e/e2e_auth_test.go
  e2e/e2e_suite_test.go
  e2e/e2e_test.go
  fleetshard/README.md
  fleetshard/config/config.go
  fleetshard/config/config_test.go
  fleetshard/pkg/runtime/runtime.go
  internal/dinosaur/pkg/environments/integration.go
  internal/dinosaur/test/integration/data_plane_endpoints_test.go
  pkg/auth/fleetshard_authz.go
  pkg/auth/fleetshard_authz_middleware.go
  pkg/auth/fleetshard_authz_middleware_test.go
  pkg/auth/fleetshard_authz_test.go
  pkg/auth/testdata/fleetshard-authz.yaml
  pkg/client/iam/config.go
  scripts/delete-central.sh
  templates/service-template.yml
  test/helper.go
Labels: approved

#1962 ROX-25389: Add namespace and label selector for Probe CRs
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
Labels: lgtm, approved

#1963 ROX-21531: Remove probe namespace selector from the Observability CR
  dp-terraform/helm/rhacs-terraform/charts/observability/templates/01-operator-06-cr.yaml
Labels: lgtm, approved
