Repository stackrox/acs-fleet-manager, pull requests merged in 2024-03, with the labels that each got.

#1686 fix: check if telemetry is enabled
  internal/dinosaur/pkg/services/telemetry.go
Labels: lgtm

#1688 Parameterize envoy resources
  templates/service-template.yml
Labels: lgtm, approved

#1680 ROX-22859: Remove unused ACS Operator template
  dp-terraform/helm/rhacs-terraform/templates/acs-operator.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1690 ROX-22887: Use go 1.20 to build images in CI
  .github/workflows/ci.yaml
  .secrets.baseline
Labels: lgtm, approved

#1691 Delete the duplicate line from the service template
  templates/service-template.yml
Labels: lgtm, approved

#1694 Rollback helm-operator to v1.33.0
  dp-terraform/helm/Dockerfile
Labels: lgtm, approved

#1665 ROX-22551: Cleanup Fleet Manager after the addon CI/CD implementation
  .secrets.baseline
  Makefile
  docs/legacy/feature-flags.md
  go.mod
  go.sum
  internal/dinosaur/pkg/config/dataplane_cluster_config.go
  internal/dinosaur/pkg/environments/development.go
  internal/dinosaur/pkg/environments/integration.go
  internal/dinosaur/pkg/environments/production.go
  internal/dinosaur/pkg/environments/stage.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/ready_dinosaurs_mgr.go
  pkg/client/iam/client.go
  pkg/client/iam/client_moq.go
  pkg/client/iam/client_test.go
  pkg/client/iam/config.go
  pkg/client/iam/gocloak_moq.go
  pkg/providers/core.go
  pkg/services/sso/iam_service.go
  pkg/services/sso/iam_service_moq.go
  pkg/services/sso/redhatsso_service.go
  templates/service-template.yml
  test/mocks/api_server.go
Labels: lgtm, approved

#1695 ROX-22926: Enable dogfood local scanner
  dp-terraform/helm/rhacs-terraform/charts/secured-cluster/templates/secured-cluster-cr.yaml
  dp-terraform/helm/rhacs-terraform/charts/secured-cluster/values.yaml
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1697 ROX-22926: Fix scannerComponent
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1699 ROX-22926: Fix scannerComponent
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1698 Disable ESO webhook
  dp-terraform/helm/Dockerfile
  dp-terraform/helm/rhacs-terraform/values.yaml
Labels: lgtm, approved

#1696 ROX-22593: git hook fix
  tools/noop.go
Labels: lgtm, approved

#1708 ROX-22361: Log ACSCS instance state change
  internal/dinosaur/pkg/services/dinosaur.go
Labels: approved

#1713 ROX-21836: Drop Envoy redundant config
  templates/service-template.yml
Labels: lgtm, approved

#1659 Deploy fleet-manager from template in e2e tests
  .dockerignore
  .openshift-ci/tests/e2e.sh
  .secrets.baseline
  Dockerfile
  Makefile
  dev/config/dataplane-cluster-configuration-crc.yaml
  dev/config/dataplane-cluster-configuration-dockerdesktop.yaml
  dev/config/dataplane-cluster-configuration-kind.yaml
  dev/config/dataplane-cluster-configuration-minikube.yaml
  dev/config/dataplane-cluster-configuration.yaml
  dev/config/gitops-config.yaml
  dev/config/provider-configuration.yaml
  dev/config/quota-management-list-configuration.yaml
  dev/env/central-to-ready/central-status-update-ready.json
  dev/env/defaults/00-defaults.env
  dev/env/defaults/cluster-type-infra-openshift/env
  dev/env/defaults/cluster-type-openshift-ci/env
  dev/env/defaults/cluster-type-openshift/env
  dev/env/manifests/db/00-db-secrets.yaml
  dev/env/manifests/db/01-db-deployment.yaml
  dev/env/manifests/db/02-db-service.yaml
  dev/env/manifests/fleet-manager/01-fleet-manager-secrets.yaml
  dev/env/manifests/fleet-manager/02-fleet-manager-deployment.yaml
  dev/env/manifests/fleet-manager/03-fleet-manager-service-active.yaml
  dev/env/manifests/fleet-manager/03-fleet-manager-service.yaml
  dev/env/manifests/fleet-manager/04-gitops-config.yaml
  dev/env/manifests/fleetshard-sync/02-fleetshard-sync-deployment.yaml
  dev/env/manifests/openshift-router/03-router.yaml
  dev/env/manifests/openshift-router/README.md
  dev/env/manifests/shared/03-configmap-config.yaml
  dev/env/scripts/bootstrap.sh
  dev/env/scripts/down.sh
  dev/env/scripts/ensure_operator_image_exists.sh
  dev/env/scripts/lib.sh
  dev/env/scripts/reset
  dev/env/scripts/up.sh
  dev/env/scripts/update_gitops_config.sh
  docs/development/setup-developer-osd-cluster.md
  e2e/e2e_canary_upgrade_test.go
  e2e/e2e_test.go
  pkg/features/list.go
  templates/db-template.yml
  templates/envoy-config-configmap.yml
  templates/gitops-template.yml
  templates/service-template.yml
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: approved

#1719 ROX-16615: Make the probe service create multiple centrals (per region / cloud provider)
  deploy/helm/probe/templates/01-operator-04-deployment.yaml
  probe/cmd/probe/main.go
  probe/config/config.go
  probe/config/config_test.go
  probe/internal/cli/cli_test.go
  probe/pkg/metrics/metrics.go
  probe/pkg/metrics/metrics_test.go
  probe/pkg/metrics/server.go
  probe/pkg/metrics/server_test.go
  probe/pkg/probe/probe.go
  probe/pkg/probe/probe_moq.go
  probe/pkg/probe/probe_test.go
  probe/pkg/runtime/runtime.go
  probe/pkg/runtime/runtime_test.go
Labels: lgtm, approved

#1722 ROX-16615: Probe template
  Makefile
  probe/README.md
  probe/config/config.go
  probe/config/config_test.go
  templates/probe-template.yml
Labels: lgtm, approved

#1721 ROX-22428: Rename dinosaurService#Update
  internal/dinosaur/pkg/services/data_plane_dinosaur.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/dinosaurservice_moq.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_auth_config_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/dinosaurs_routes_cname_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/preparing_dinosaurs_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/timeout.go
Labels: lgtm, approved

#1720 ROX-22428: Use `sql.NullTime` instead of `*time.Time` in `dbapi`
  internal/dinosaur/pkg/api/dbapi/central_request_types.go
  internal/dinosaur/pkg/api/dbapi/central_request_types_test.go
  internal/dinosaur/pkg/presenters/admin_dinosaur.go
  internal/dinosaur/pkg/presenters/managedcentral.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/telemetry.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/expiration_date_mgr.go
  internal/dinosaur/pkg/workers/dinosaurmgrs/expiration_date_mgr_test.go
  pkg/db/model_type_check.go
  pkg/db/model_type_check_test.go
Labels: lgtm, approved

#1723 ROX-21682: Add support for central-encryption-key-chain
  e2e/e2e_test.go
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
  fleetshard/pkg/k8s/secret.go
Labels: approved

#1724 ROX-22557: Expiration central count grafana panel
  dashboards/grafana-dashboard-acs-fleet-manager.configmap.yaml
Labels: lgtm, approved

#1727 ROX-21682: remove double base64 encoding
  fleetshard/pkg/central/reconciler/reconciler.go
  fleetshard/pkg/central/reconciler/reconciler_test.go
Labels: lgtm, approved

#1598 ROX-16587: API for switching billing model of a central
  .secrets.baseline
  internal/dinosaur/pkg/api/admin/private/api/openapi.yaml
  internal/dinosaur/pkg/api/admin/private/api_default.go
  internal/dinosaur/pkg/api/admin/private/model_central_billing_change_request.go
  internal/dinosaur/pkg/converters/dinosaur_request.go
  internal/dinosaur/pkg/handlers/admin_dinosaur.go
  internal/dinosaur/pkg/routes/route_loader.go
  internal/dinosaur/pkg/services/dinosaur.go
  internal/dinosaur/pkg/services/dinosaur_test.go
  internal/dinosaur/pkg/services/dinosaurservice_moq.go
  internal/dinosaur/pkg/services/quota.go
  internal/dinosaur/pkg/services/quota/ams_quota_service.go
  internal/dinosaur/pkg/services/quota/ams_quota_service_test.go
  internal/dinosaur/pkg/services/quota/quota_management_list_service.go
  internal/dinosaur/pkg/services/quota/quota_management_list_service_test.go
  internal/dinosaur/pkg/services/quotaservice_moq.go
  openapi/fleet-manager-private-admin.yaml
Labels: approved

#1731 chore(probe): unset cpu limits
  deploy/helm/probe/templates/01-secret-ocm-token.yaml
  deploy/helm/probe/templates/01-secret-rhsso-client-secret.yaml
  deploy/helm/probe/templates/02-deployment.yaml
  deploy/helm/probe/values.yaml
  templates/probe-template.yml
Labels: lgtm, approved
